// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_USER        UserRole = 1
	UserRole_USER_ROLE_ADMIN       UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_USER",
		2: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_USER":        1,
		"USER_ROLE_ADMIN":       2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_BLOCKED     UserStatus = 2
	UserStatus_USER_STATUS_DELETED     UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_BLOCKED",
		3: "USER_STATUS_DELETED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_BLOCKED":     2,
		"USER_STATUS_DELETED":     3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

type RepositoryVisibility int32

const (
	RepositoryVisibility_REPOSITORY_VISIBILITY_UNSPECIFIED RepositoryVisibility = 0
	RepositoryVisibility_REPOSITORY_VISIBILITY_PUBLIC      RepositoryVisibility = 1
	RepositoryVisibility_REPOSITORY_VISIBILITY_PRIVATE     RepositoryVisibility = 2
)

// Enum value maps for RepositoryVisibility.
var (
	RepositoryVisibility_name = map[int32]string{
		0: "REPOSITORY_VISIBILITY_UNSPECIFIED",
		1: "REPOSITORY_VISIBILITY_PUBLIC",
		2: "REPOSITORY_VISIBILITY_PRIVATE",
	}
	RepositoryVisibility_value = map[string]int32{
		"REPOSITORY_VISIBILITY_UNSPECIFIED": 0,
		"REPOSITORY_VISIBILITY_PUBLIC":      1,
		"REPOSITORY_VISIBILITY_PRIVATE":     2,
	}
)

func (x RepositoryVisibility) Enum() *RepositoryVisibility {
	p := new(RepositoryVisibility)
	*p = x
	return p
}

func (x RepositoryVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepositoryVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[2].Descriptor()
}

func (RepositoryVisibility) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[2]
}

func (x RepositoryVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepositoryVisibility.Descriptor instead.
func (RepositoryVisibility) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{2}
}

type RepositoryType int32

const (
	RepositoryType_REPOSITORY_TYPE_UNSPECIFIED RepositoryType = 0
	RepositoryType_REPOSITORY_TYPE_ARTICLE     RepositoryType = 1
	RepositoryType_REPOSITORY_TYPE_NOTES       RepositoryType = 2
	RepositoryType_REPOSITORY_TYPE_MIXED       RepositoryType = 3
)

// Enum value maps for RepositoryType.
var (
	RepositoryType_name = map[int32]string{
		0: "REPOSITORY_TYPE_UNSPECIFIED",
		1: "REPOSITORY_TYPE_ARTICLE",
		2: "REPOSITORY_TYPE_NOTES",
		3: "REPOSITORY_TYPE_MIXED",
	}
	RepositoryType_value = map[string]int32{
		"REPOSITORY_TYPE_UNSPECIFIED": 0,
		"REPOSITORY_TYPE_ARTICLE":     1,
		"REPOSITORY_TYPE_NOTES":       2,
		"REPOSITORY_TYPE_MIXED":       3,
	}
)

func (x RepositoryType) Enum() *RepositoryType {
	p := new(RepositoryType)
	*p = x
	return p
}

func (x RepositoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepositoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[3].Descriptor()
}

func (RepositoryType) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[3]
}

func (x RepositoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepositoryType.Descriptor instead.
func (RepositoryType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{3}
}

type DocumentFormat int32

const (
	DocumentFormat_DOCUMENT_FORMAT_UNSPECIFIED DocumentFormat = 0
	DocumentFormat_DOCUMENT_FORMAT_MARKDOWN    DocumentFormat = 1
)

// Enum value maps for DocumentFormat.
var (
	DocumentFormat_name = map[int32]string{
		0: "DOCUMENT_FORMAT_UNSPECIFIED",
		1: "DOCUMENT_FORMAT_MARKDOWN",
	}
	DocumentFormat_value = map[string]int32{
		"DOCUMENT_FORMAT_UNSPECIFIED": 0,
		"DOCUMENT_FORMAT_MARKDOWN":    1,
	}
)

func (x DocumentFormat) Enum() *DocumentFormat {
	p := new(DocumentFormat)
	*p = x
	return p
}

func (x DocumentFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[4].Descriptor()
}

func (DocumentFormat) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[4]
}

func (x DocumentFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentFormat.Descriptor instead.
func (DocumentFormat) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{4}
}

type SearchEntityType int32

const (
	SearchEntityType_SEARCH_ENTITY_TYPE_UNSPECIFIED SearchEntityType = 0
	SearchEntityType_SEARCH_ENTITY_TYPE_REPOSITORY  SearchEntityType = 1
	SearchEntityType_SEARCH_ENTITY_TYPE_DOCUMENT    SearchEntityType = 2
	SearchEntityType_SEARCH_ENTITY_TYPE_FILE        SearchEntityType = 3
)

// Enum value maps for SearchEntityType.
var (
	SearchEntityType_name = map[int32]string{
		0: "SEARCH_ENTITY_TYPE_UNSPECIFIED",
		1: "SEARCH_ENTITY_TYPE_REPOSITORY",
		2: "SEARCH_ENTITY_TYPE_DOCUMENT",
		3: "SEARCH_ENTITY_TYPE_FILE",
	}
	SearchEntityType_value = map[string]int32{
		"SEARCH_ENTITY_TYPE_UNSPECIFIED": 0,
		"SEARCH_ENTITY_TYPE_REPOSITORY":  1,
		"SEARCH_ENTITY_TYPE_DOCUMENT":    2,
		"SEARCH_ENTITY_TYPE_FILE":        3,
	}
)

func (x SearchEntityType) Enum() *SearchEntityType {
	p := new(SearchEntityType)
	*p = x
	return p
}

func (x SearchEntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchEntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[5].Descriptor()
}

func (SearchEntityType) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[5]
}

func (x SearchEntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchEntityType.Descriptor instead.
func (SearchEntityType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{5}
}

type SearchEventType int32

const (
	SearchEventType_SEARCH_EVENT_TYPE_UNSPECIFIED         SearchEventType = 0
	SearchEventType_SEARCH_EVENT_TYPE_REPOSITORY_UPSERTED SearchEventType = 1
	SearchEventType_SEARCH_EVENT_TYPE_REPOSITORY_DELETED  SearchEventType = 2
	SearchEventType_SEARCH_EVENT_TYPE_DOCUMENT_UPSERTED   SearchEventType = 3
	SearchEventType_SEARCH_EVENT_TYPE_DOCUMENT_DELETED    SearchEventType = 4
	SearchEventType_SEARCH_EVENT_TYPE_FILE_UPSERTED       SearchEventType = 5
	SearchEventType_SEARCH_EVENT_TYPE_FILE_DELETED        SearchEventType = 6
)

// Enum value maps for SearchEventType.
var (
	SearchEventType_name = map[int32]string{
		0: "SEARCH_EVENT_TYPE_UNSPECIFIED",
		1: "SEARCH_EVENT_TYPE_REPOSITORY_UPSERTED",
		2: "SEARCH_EVENT_TYPE_REPOSITORY_DELETED",
		3: "SEARCH_EVENT_TYPE_DOCUMENT_UPSERTED",
		4: "SEARCH_EVENT_TYPE_DOCUMENT_DELETED",
		5: "SEARCH_EVENT_TYPE_FILE_UPSERTED",
		6: "SEARCH_EVENT_TYPE_FILE_DELETED",
	}
	SearchEventType_value = map[string]int32{
		"SEARCH_EVENT_TYPE_UNSPECIFIED":         0,
		"SEARCH_EVENT_TYPE_REPOSITORY_UPSERTED": 1,
		"SEARCH_EVENT_TYPE_REPOSITORY_DELETED":  2,
		"SEARCH_EVENT_TYPE_DOCUMENT_UPSERTED":   3,
		"SEARCH_EVENT_TYPE_DOCUMENT_DELETED":    4,
		"SEARCH_EVENT_TYPE_FILE_UPSERTED":       5,
		"SEARCH_EVENT_TYPE_FILE_DELETED":        6,
	}
)

func (x SearchEventType) Enum() *SearchEventType {
	p := new(SearchEventType)
	*p = x
	return p
}

func (x SearchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[6].Descriptor()
}

func (SearchEventType) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[6]
}

func (x SearchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchEventType.Descriptor instead.
func (SearchEventType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{6}
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_common_v1_common_proto protoreflect.FileDescriptor

const file_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/common.proto\x12\x12forklore.common.v1\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value*N\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x01\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x02*s\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x17\n" +
	"\x13USER_STATUS_BLOCKED\x10\x02\x12\x17\n" +
	"\x13USER_STATUS_DELETED\x10\x03*\x82\x01\n" +
	"\x14RepositoryVisibility\x12%\n" +
	"!REPOSITORY_VISIBILITY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cREPOSITORY_VISIBILITY_PUBLIC\x10\x01\x12!\n" +
	"\x1dREPOSITORY_VISIBILITY_PRIVATE\x10\x02*\x84\x01\n" +
	"\x0eRepositoryType\x12\x1f\n" +
	"\x1bREPOSITORY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17REPOSITORY_TYPE_ARTICLE\x10\x01\x12\x19\n" +
	"\x15REPOSITORY_TYPE_NOTES\x10\x02\x12\x19\n" +
	"\x15REPOSITORY_TYPE_MIXED\x10\x03*O\n" +
	"\x0eDocumentFormat\x12\x1f\n" +
	"\x1bDOCUMENT_FORMAT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DOCUMENT_FORMAT_MARKDOWN\x10\x01*\x97\x01\n" +
	"\x10SearchEntityType\x12\"\n" +
	"\x1eSEARCH_ENTITY_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSEARCH_ENTITY_TYPE_REPOSITORY\x10\x01\x12\x1f\n" +
	"\x1bSEARCH_ENTITY_TYPE_DOCUMENT\x10\x02\x12\x1b\n" +
	"\x17SEARCH_ENTITY_TYPE_FILE\x10\x03*\xa3\x02\n" +
	"\x0fSearchEventType\x12!\n" +
	"\x1dSEARCH_EVENT_TYPE_UNSPECIFIED\x10\x00\x12)\n" +
	"%SEARCH_EVENT_TYPE_REPOSITORY_UPSERTED\x10\x01\x12(\n" +
	"$SEARCH_EVENT_TYPE_REPOSITORY_DELETED\x10\x02\x12'\n" +
	"#SEARCH_EVENT_TYPE_DOCUMENT_UPSERTED\x10\x03\x12&\n" +
	"\"SEARCH_EVENT_TYPE_DOCUMENT_DELETED\x10\x04\x12#\n" +
	"\x1fSEARCH_EVENT_TYPE_FILE_UPSERTED\x10\x05\x12\"\n" +
	"\x1eSEARCH_EVENT_TYPE_FILE_DELETED\x10\x06B9Z7github.com/Anabol1ks/Forklore/pkg/pb/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_common_proto_rawDescOnce sync.Once
	file_common_v1_common_proto_rawDescData []byte
)

func file_common_v1_common_proto_rawDescGZIP() []byte {
	file_common_v1_common_proto_rawDescOnce.Do(func() {
		file_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)))
	})
	return file_common_v1_common_proto_rawDescData
}

var file_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_common_proto_goTypes = []any{
	(UserRole)(0),             // 0: forklore.common.v1.UserRole
	(UserStatus)(0),           // 1: forklore.common.v1.UserStatus
	(RepositoryVisibility)(0), // 2: forklore.common.v1.RepositoryVisibility
	(RepositoryType)(0),       // 3: forklore.common.v1.RepositoryType
	(DocumentFormat)(0),       // 4: forklore.common.v1.DocumentFormat
	(SearchEntityType)(0),     // 5: forklore.common.v1.SearchEntityType
	(SearchEventType)(0),      // 6: forklore.common.v1.SearchEventType
	(*UUID)(nil),              // 7: forklore.common.v1.UUID
}
var file_common_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_common_proto_init() }
func file_common_v1_common_proto_init() {
	if File_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_common_proto_goTypes,
		DependencyIndexes: file_common_v1_common_proto_depIdxs,
		EnumInfos:         file_common_v1_common_proto_enumTypes,
		MessageInfos:      file_common_v1_common_proto_msgTypes,
	}.Build()
	File_common_v1_common_proto = out.File
	file_common_v1_common_proto_goTypes = nil
	file_common_v1_common_proto_depIdxs = nil
}
