services:
  auth-db:
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_AUTH_USER}
      POSTGRES_PASSWORD: ${DB_AUTH_PASSWORD}
      POSTGRES_DB: auth-db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_AUTH_USER} -d ${DB_AUTH_NAME} -h localhost -p 5432 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - forklore-network

  repo-db:
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_REPO_USER}
      POSTGRES_PASSWORD: ${DB_REPO_PASSWORD}
      POSTGRES_DB: repo-db
    volumes:
      - repo_db_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_REPO_USER} -d ${DB_REPO_NAME} -h localhost -p 5432 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - forklore-network

  content-db:
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_CONTENT_USER}
      POSTGRES_PASSWORD: ${DB_CONTENT_PASSWORD}
      POSTGRES_DB: content-db
    volumes:
      - content_db_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_CONTENT_USER} -d ${DB_CONTENT_NAME} -h localhost -p 5432 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - forklore-network


volumes:
  auth_db_data:
  repo_db_data:
  content_db_data:

networks:
  forklore-network:
    driver: bridge