// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: repository/v1/repository.proto

package repositoryv1

import (
	v1 "github.com/Anabol1ks/Forklore/pkg/pb/common/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repository struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RepoId        *v1.UUID                `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	OwnerId       *v1.UUID                `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                  `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                  `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    v1.RepositoryVisibility `protobuf:"varint,6,opt,name=visibility,proto3,enum=forklore.common.v1.RepositoryVisibility" json:"visibility,omitempty"`
	Type          v1.RepositoryType       `protobuf:"varint,7,opt,name=type,proto3,enum=forklore.common.v1.RepositoryType" json:"type,omitempty"`
	ParentRepoId  *v1.UUID                `protobuf:"bytes,8,opt,name=parent_repo_id,json=parentRepoId,proto3" json:"parent_repo_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_repository_v1_repository_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{0}
}

func (x *Repository) GetRepoId() *v1.UUID {
	if x != nil {
		return x.RepoId
	}
	return nil
}

func (x *Repository) GetOwnerId() *v1.UUID {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repository) GetVisibility() v1.RepositoryVisibility {
	if x != nil {
		return x.Visibility
	}
	return v1.RepositoryVisibility(0)
}

func (x *Repository) GetType() v1.RepositoryType {
	if x != nil {
		return x.Type
	}
	return v1.RepositoryType(0)
}

func (x *Repository) GetParentRepoId() *v1.UUID {
	if x != nil {
		return x.ParentRepoId
	}
	return nil
}

func (x *Repository) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Repository) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Repository) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreateRepositoryRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                  `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    v1.RepositoryVisibility `protobuf:"varint,4,opt,name=visibility,proto3,enum=forklore.common.v1.RepositoryVisibility" json:"visibility,omitempty"`
	Type          v1.RepositoryType       `protobuf:"varint,5,opt,name=type,proto3,enum=forklore.common.v1.RepositoryType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepositoryRequest) Reset() {
	*x = CreateRepositoryRequest{}
	mi := &file_repository_v1_repository_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepositoryRequest) ProtoMessage() {}

func (x *CreateRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepositoryRequest.ProtoReflect.Descriptor instead.
func (*CreateRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRepositoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRepositoryRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateRepositoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRepositoryRequest) GetVisibility() v1.RepositoryVisibility {
	if x != nil {
		return x.Visibility
	}
	return v1.RepositoryVisibility(0)
}

func (x *CreateRepositoryRequest) GetType() v1.RepositoryType {
	if x != nil {
		return x.Type
	}
	return v1.RepositoryType(0)
}

type CreateRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepositoryResponse) Reset() {
	*x = CreateRepositoryResponse{}
	mi := &file_repository_v1_repository_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepositoryResponse) ProtoMessage() {}

func (x *CreateRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepositoryResponse.ProtoReflect.Descriptor instead.
func (*CreateRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type GetRepositoryByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        *v1.UUID               `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryByIdRequest) Reset() {
	*x = GetRepositoryByIdRequest{}
	mi := &file_repository_v1_repository_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryByIdRequest) ProtoMessage() {}

func (x *GetRepositoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{3}
}

func (x *GetRepositoryByIdRequest) GetRepoId() *v1.UUID {
	if x != nil {
		return x.RepoId
	}
	return nil
}

type GetRepositoryBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       *v1.UUID               `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryBySlugRequest) Reset() {
	*x = GetRepositoryBySlugRequest{}
	mi := &file_repository_v1_repository_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryBySlugRequest) ProtoMessage() {}

func (x *GetRepositoryBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryBySlugRequest) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{4}
}

func (x *GetRepositoryBySlugRequest) GetOwnerId() *v1.UUID {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *GetRepositoryBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryResponse) Reset() {
	*x = GetRepositoryResponse{}
	mi := &file_repository_v1_repository_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryResponse) ProtoMessage() {}

func (x *GetRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{5}
}

func (x *GetRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type UpdateRepositoryRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RepoId        *v1.UUID                `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                  `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    v1.RepositoryVisibility `protobuf:"varint,5,opt,name=visibility,proto3,enum=forklore.common.v1.RepositoryVisibility" json:"visibility,omitempty"`
	Type          v1.RepositoryType       `protobuf:"varint,6,opt,name=type,proto3,enum=forklore.common.v1.RepositoryType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepositoryRequest) Reset() {
	*x = UpdateRepositoryRequest{}
	mi := &file_repository_v1_repository_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepositoryRequest) ProtoMessage() {}

func (x *UpdateRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepositoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRepositoryRequest) GetRepoId() *v1.UUID {
	if x != nil {
		return x.RepoId
	}
	return nil
}

func (x *UpdateRepositoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRepositoryRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateRepositoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRepositoryRequest) GetVisibility() v1.RepositoryVisibility {
	if x != nil {
		return x.Visibility
	}
	return v1.RepositoryVisibility(0)
}

func (x *UpdateRepositoryRequest) GetType() v1.RepositoryType {
	if x != nil {
		return x.Type
	}
	return v1.RepositoryType(0)
}

type UpdateRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepositoryResponse) Reset() {
	*x = UpdateRepositoryResponse{}
	mi := &file_repository_v1_repository_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepositoryResponse) ProtoMessage() {}

func (x *UpdateRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepositoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type DeleteRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        *v1.UUID               `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepositoryRequest) Reset() {
	*x = DeleteRepositoryRequest{}
	mi := &file_repository_v1_repository_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepositoryRequest) ProtoMessage() {}

func (x *DeleteRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepositoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRepositoryRequest) GetRepoId() *v1.UUID {
	if x != nil {
		return x.RepoId
	}
	return nil
}

type ForkRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceRepoId  *v1.UUID               `protobuf:"bytes,1,opt,name=source_repo_id,json=sourceRepoId,proto3" json:"source_repo_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkRepositoryRequest) Reset() {
	*x = ForkRepositoryRequest{}
	mi := &file_repository_v1_repository_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRepositoryRequest) ProtoMessage() {}

func (x *ForkRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRepositoryRequest.ProtoReflect.Descriptor instead.
func (*ForkRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{9}
}

func (x *ForkRepositoryRequest) GetSourceRepoId() *v1.UUID {
	if x != nil {
		return x.SourceRepoId
	}
	return nil
}

func (x *ForkRepositoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForkRepositoryRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ForkRepositoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ForkRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkRepositoryResponse) Reset() {
	*x = ForkRepositoryResponse{}
	mi := &file_repository_v1_repository_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRepositoryResponse) ProtoMessage() {}

func (x *ForkRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRepositoryResponse.ProtoReflect.Descriptor instead.
func (*ForkRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{10}
}

func (x *ForkRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type ListMyRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyRepositoriesRequest) Reset() {
	*x = ListMyRepositoriesRequest{}
	mi := &file_repository_v1_repository_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyRepositoriesRequest) ProtoMessage() {}

func (x *ListMyRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListMyRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{11}
}

func (x *ListMyRepositoriesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMyRepositoriesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUserRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       *v1.UUID               `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRepositoriesRequest) Reset() {
	*x = ListUserRepositoriesRequest{}
	mi := &file_repository_v1_repository_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRepositoriesRequest) ProtoMessage() {}

func (x *ListUserRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListUserRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserRepositoriesRequest) GetOwnerId() *v1.UUID {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *ListUserRepositoriesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserRepositoriesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListForksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        *v1.UUID               `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListForksRequest) Reset() {
	*x = ListForksRequest{}
	mi := &file_repository_v1_repository_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListForksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListForksRequest) ProtoMessage() {}

func (x *ListForksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListForksRequest.ProtoReflect.Descriptor instead.
func (*ListForksRequest) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{13}
}

func (x *ListForksRequest) GetRepoId() *v1.UUID {
	if x != nil {
		return x.RepoId
	}
	return nil
}

func (x *ListForksRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListForksRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesResponse) Reset() {
	*x = ListRepositoriesResponse{}
	mi := &file_repository_v1_repository_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesResponse) ProtoMessage() {}

func (x *ListRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_v1_repository_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_repository_v1_repository_proto_rawDescGZIP(), []int{14}
}

func (x *ListRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *ListRepositoriesResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_repository_v1_repository_proto protoreflect.FileDescriptor

const file_repository_v1_repository_proto_rawDesc = "" +
	"\n" +
	"\x1erepository/v1/repository.proto\x12\x16forklore.repository.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x16common/v1/common.proto\"\x97\x05\n" +
	"\n" +
	"Repository\x12;\n" +
	"\arepo_id\x18\x01 \x01(\v2\x18.forklore.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06repoId\x12=\n" +
	"\bowner_id\x18\x02 \x01(\v2\x18.forklore.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aownerId\x12\x1d\n" +
	"\x04name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18dR\x04name\x12E\n" +
	"\x04slug\x18\x04 \x01(\tB1\xfaB.r,\x10\x03\x18@2&^[a-z0-9](?:[a-z0-9-]{1,62}[a-z0-9])?$R\x04slug\x12*\n" +
	"\vdescription\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x18\xd0\x0fR\vdescription\x12H\n" +
	"\n" +
	"visibility\x18\x06 \x01(\x0e2(.forklore.common.v1.RepositoryVisibilityR\n" +
	"visibility\x126\n" +
	"\x04type\x18\a \x01(\x0e2\".forklore.common.v1.RepositoryTypeR\x04type\x12>\n" +
	"\x0eparent_repo_id\x18\b \x01(\v2\x18.forklore.common.v1.UUIDR\fparentRepoId\x12C\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x83\x02\n" +
	"\x17CreateRepositoryRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18dR\x04name\x12\x1b\n" +
	"\x04slug\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18@R\x04slug\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xd0\x0fR\vdescription\x12H\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2(.forklore.common.v1.RepositoryVisibilityR\n" +
	"visibility\x126\n" +
	"\x04type\x18\x05 \x01(\x0e2\".forklore.common.v1.RepositoryTypeR\x04type\"^\n" +
	"\x18CreateRepositoryResponse\x12B\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\".forklore.repository.v1.RepositoryR\n" +
	"repository\"W\n" +
	"\x18GetRepositoryByIdRequest\x12;\n" +
	"\arepo_id\x18\x01 \x01(\v2\x18.forklore.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06repoId\"\xa2\x01\n" +
	"\x1aGetRepositoryBySlugRequest\x12=\n" +
	"\bowner_id\x18\x01 \x01(\v2\x18.forklore.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aownerId\x12E\n" +
	"\x04slug\x18\x02 \x01(\tB1\xfaB.r,\x10\x03\x18@2&^[a-z0-9](?:[a-z0-9-]{1,62}[a-z0-9])?$R\x04slug\"[\n" +
	"\x15GetRepositoryResponse\x12B\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\".forklore.repository.v1.RepositoryR\n" +
	"repository\"\xea\x02\n" +
	"\x17UpdateRepositoryRequest\x12;\n" +
	"\arepo_id\x18\x01 \x01(\v2\x18.forklore.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06repoId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18dR\x04name\x12E\n" +
	"\x04slug\x18\x03 \x01(\tB1\xfaB.r,\x10\x03\x18@2&^[a-z0-9](?:[a-z0-9-]{1,62}[a-z0-9])?$R\x04slug\x12*\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x18\xd0\x0fR\vdescription\x12H\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2(.forklore.common.v1.RepositoryVisibilityR\n" +
	"visibility\x126\n" +
	"\x04type\x18\x06 \x01(\x0e2\".forklore.common.v1.RepositoryTypeR\x04type\"^\n" +
	"\x18UpdateRepositoryResponse\x12B\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\".forklore.repository.v1.RepositoryR\n" +
	"repository\"V\n" +
	"\x17DeleteRepositoryRequest\x12;\n" +
	"\arepo_id\x18\x01 \x01(\v2\x18.forklore.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06repoId\"\xc7\x01\n" +
	"\x15ForkRepositoryRequest\x12H\n" +
	"\x0esource_repo_id\x18\x01 \x01(\v2\x18.forklore.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\fsourceRepoId\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18dR\x04name\x12\x1b\n" +
	"\x04slug\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18@R\x04slug\x12*\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x18\xd0\x0fR\vdescription\"\\\n" +
	"\x16ForkRepositoryResponse\x12B\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\".forklore.repository.v1.RepositoryR\n" +
	"repository\"T\n" +
	"\x19ListMyRepositoriesRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\rB\t\xfaB\x06*\x04\x18d(\x01R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"\x95\x01\n" +
	"\x1bListUserRepositoriesRequest\x12=\n" +
	"\bowner_id\x18\x01 \x01(\v2\x18.forklore.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aownerId\x12\x1f\n" +
	"\x05limit\x18\x02 \x01(\rB\t\xfaB\x06*\x04\x18d(\x01R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"\x88\x01\n" +
	"\x10ListForksRequest\x12;\n" +
	"\arepo_id\x18\x01 \x01(\v2\x18.forklore.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06repoId\x12\x1f\n" +
	"\x05limit\x18\x02 \x01(\rB\t\xfaB\x06*\x04\x18d(\x01R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"x\n" +
	"\x18ListRepositoriesResponse\x12F\n" +
	"\frepositories\x18\x01 \x03(\v2\".forklore.repository.v1.RepositoryR\frepositories\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total2\xa2\b\n" +
	"\x11RepositoryService\x12u\n" +
	"\x10CreateRepository\x12/.forklore.repository.v1.CreateRepositoryRequest\x1a0.forklore.repository.v1.CreateRepositoryResponse\x12t\n" +
	"\x11GetRepositoryById\x120.forklore.repository.v1.GetRepositoryByIdRequest\x1a-.forklore.repository.v1.GetRepositoryResponse\x12x\n" +
	"\x13GetRepositoryBySlug\x122.forklore.repository.v1.GetRepositoryBySlugRequest\x1a-.forklore.repository.v1.GetRepositoryResponse\x12u\n" +
	"\x10UpdateRepository\x12/.forklore.repository.v1.UpdateRepositoryRequest\x1a0.forklore.repository.v1.UpdateRepositoryResponse\x12[\n" +
	"\x10DeleteRepository\x12/.forklore.repository.v1.DeleteRepositoryRequest\x1a\x16.google.protobuf.Empty\x12o\n" +
	"\x0eForkRepository\x12-.forklore.repository.v1.ForkRepositoryRequest\x1a..forklore.repository.v1.ForkRepositoryResponse\x12y\n" +
	"\x12ListMyRepositories\x121.forklore.repository.v1.ListMyRepositoriesRequest\x1a0.forklore.repository.v1.ListRepositoriesResponse\x12}\n" +
	"\x14ListUserRepositories\x123.forklore.repository.v1.ListUserRepositoriesRequest\x1a0.forklore.repository.v1.ListRepositoriesResponse\x12g\n" +
	"\tListForks\x12(.forklore.repository.v1.ListForksRequest\x1a0.forklore.repository.v1.ListRepositoriesResponseBAZ?github.com/Anabol1ks/Forklore/pkg/pb/repository/v1;repositoryv1b\x06proto3"

var (
	file_repository_v1_repository_proto_rawDescOnce sync.Once
	file_repository_v1_repository_proto_rawDescData []byte
)

func file_repository_v1_repository_proto_rawDescGZIP() []byte {
	file_repository_v1_repository_proto_rawDescOnce.Do(func() {
		file_repository_v1_repository_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_v1_repository_proto_rawDesc), len(file_repository_v1_repository_proto_rawDesc)))
	})
	return file_repository_v1_repository_proto_rawDescData
}

var file_repository_v1_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_repository_v1_repository_proto_goTypes = []any{
	(*Repository)(nil),                  // 0: forklore.repository.v1.Repository
	(*CreateRepositoryRequest)(nil),     // 1: forklore.repository.v1.CreateRepositoryRequest
	(*CreateRepositoryResponse)(nil),    // 2: forklore.repository.v1.CreateRepositoryResponse
	(*GetRepositoryByIdRequest)(nil),    // 3: forklore.repository.v1.GetRepositoryByIdRequest
	(*GetRepositoryBySlugRequest)(nil),  // 4: forklore.repository.v1.GetRepositoryBySlugRequest
	(*GetRepositoryResponse)(nil),       // 5: forklore.repository.v1.GetRepositoryResponse
	(*UpdateRepositoryRequest)(nil),     // 6: forklore.repository.v1.UpdateRepositoryRequest
	(*UpdateRepositoryResponse)(nil),    // 7: forklore.repository.v1.UpdateRepositoryResponse
	(*DeleteRepositoryRequest)(nil),     // 8: forklore.repository.v1.DeleteRepositoryRequest
	(*ForkRepositoryRequest)(nil),       // 9: forklore.repository.v1.ForkRepositoryRequest
	(*ForkRepositoryResponse)(nil),      // 10: forklore.repository.v1.ForkRepositoryResponse
	(*ListMyRepositoriesRequest)(nil),   // 11: forklore.repository.v1.ListMyRepositoriesRequest
	(*ListUserRepositoriesRequest)(nil), // 12: forklore.repository.v1.ListUserRepositoriesRequest
	(*ListForksRequest)(nil),            // 13: forklore.repository.v1.ListForksRequest
	(*ListRepositoriesResponse)(nil),    // 14: forklore.repository.v1.ListRepositoriesResponse
	(*v1.UUID)(nil),                     // 15: forklore.common.v1.UUID
	(v1.RepositoryVisibility)(0),        // 16: forklore.common.v1.RepositoryVisibility
	(v1.RepositoryType)(0),              // 17: forklore.common.v1.RepositoryType
	(*timestamppb.Timestamp)(nil),       // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 19: google.protobuf.Empty
}
var file_repository_v1_repository_proto_depIdxs = []int32{
	15, // 0: forklore.repository.v1.Repository.repo_id:type_name -> forklore.common.v1.UUID
	15, // 1: forklore.repository.v1.Repository.owner_id:type_name -> forklore.common.v1.UUID
	16, // 2: forklore.repository.v1.Repository.visibility:type_name -> forklore.common.v1.RepositoryVisibility
	17, // 3: forklore.repository.v1.Repository.type:type_name -> forklore.common.v1.RepositoryType
	15, // 4: forklore.repository.v1.Repository.parent_repo_id:type_name -> forklore.common.v1.UUID
	18, // 5: forklore.repository.v1.Repository.created_at:type_name -> google.protobuf.Timestamp
	18, // 6: forklore.repository.v1.Repository.updated_at:type_name -> google.protobuf.Timestamp
	18, // 7: forklore.repository.v1.Repository.deleted_at:type_name -> google.protobuf.Timestamp
	16, // 8: forklore.repository.v1.CreateRepositoryRequest.visibility:type_name -> forklore.common.v1.RepositoryVisibility
	17, // 9: forklore.repository.v1.CreateRepositoryRequest.type:type_name -> forklore.common.v1.RepositoryType
	0,  // 10: forklore.repository.v1.CreateRepositoryResponse.repository:type_name -> forklore.repository.v1.Repository
	15, // 11: forklore.repository.v1.GetRepositoryByIdRequest.repo_id:type_name -> forklore.common.v1.UUID
	15, // 12: forklore.repository.v1.GetRepositoryBySlugRequest.owner_id:type_name -> forklore.common.v1.UUID
	0,  // 13: forklore.repository.v1.GetRepositoryResponse.repository:type_name -> forklore.repository.v1.Repository
	15, // 14: forklore.repository.v1.UpdateRepositoryRequest.repo_id:type_name -> forklore.common.v1.UUID
	16, // 15: forklore.repository.v1.UpdateRepositoryRequest.visibility:type_name -> forklore.common.v1.RepositoryVisibility
	17, // 16: forklore.repository.v1.UpdateRepositoryRequest.type:type_name -> forklore.common.v1.RepositoryType
	0,  // 17: forklore.repository.v1.UpdateRepositoryResponse.repository:type_name -> forklore.repository.v1.Repository
	15, // 18: forklore.repository.v1.DeleteRepositoryRequest.repo_id:type_name -> forklore.common.v1.UUID
	15, // 19: forklore.repository.v1.ForkRepositoryRequest.source_repo_id:type_name -> forklore.common.v1.UUID
	0,  // 20: forklore.repository.v1.ForkRepositoryResponse.repository:type_name -> forklore.repository.v1.Repository
	15, // 21: forklore.repository.v1.ListUserRepositoriesRequest.owner_id:type_name -> forklore.common.v1.UUID
	15, // 22: forklore.repository.v1.ListForksRequest.repo_id:type_name -> forklore.common.v1.UUID
	0,  // 23: forklore.repository.v1.ListRepositoriesResponse.repositories:type_name -> forklore.repository.v1.Repository
	1,  // 24: forklore.repository.v1.RepositoryService.CreateRepository:input_type -> forklore.repository.v1.CreateRepositoryRequest
	3,  // 25: forklore.repository.v1.RepositoryService.GetRepositoryById:input_type -> forklore.repository.v1.GetRepositoryByIdRequest
	4,  // 26: forklore.repository.v1.RepositoryService.GetRepositoryBySlug:input_type -> forklore.repository.v1.GetRepositoryBySlugRequest
	6,  // 27: forklore.repository.v1.RepositoryService.UpdateRepository:input_type -> forklore.repository.v1.UpdateRepositoryRequest
	8,  // 28: forklore.repository.v1.RepositoryService.DeleteRepository:input_type -> forklore.repository.v1.DeleteRepositoryRequest
	9,  // 29: forklore.repository.v1.RepositoryService.ForkRepository:input_type -> forklore.repository.v1.ForkRepositoryRequest
	11, // 30: forklore.repository.v1.RepositoryService.ListMyRepositories:input_type -> forklore.repository.v1.ListMyRepositoriesRequest
	12, // 31: forklore.repository.v1.RepositoryService.ListUserRepositories:input_type -> forklore.repository.v1.ListUserRepositoriesRequest
	13, // 32: forklore.repository.v1.RepositoryService.ListForks:input_type -> forklore.repository.v1.ListForksRequest
	2,  // 33: forklore.repository.v1.RepositoryService.CreateRepository:output_type -> forklore.repository.v1.CreateRepositoryResponse
	5,  // 34: forklore.repository.v1.RepositoryService.GetRepositoryById:output_type -> forklore.repository.v1.GetRepositoryResponse
	5,  // 35: forklore.repository.v1.RepositoryService.GetRepositoryBySlug:output_type -> forklore.repository.v1.GetRepositoryResponse
	7,  // 36: forklore.repository.v1.RepositoryService.UpdateRepository:output_type -> forklore.repository.v1.UpdateRepositoryResponse
	19, // 37: forklore.repository.v1.RepositoryService.DeleteRepository:output_type -> google.protobuf.Empty
	10, // 38: forklore.repository.v1.RepositoryService.ForkRepository:output_type -> forklore.repository.v1.ForkRepositoryResponse
	14, // 39: forklore.repository.v1.RepositoryService.ListMyRepositories:output_type -> forklore.repository.v1.ListRepositoriesResponse
	14, // 40: forklore.repository.v1.RepositoryService.ListUserRepositories:output_type -> forklore.repository.v1.ListRepositoriesResponse
	14, // 41: forklore.repository.v1.RepositoryService.ListForks:output_type -> forklore.repository.v1.ListRepositoriesResponse
	33, // [33:42] is the sub-list for method output_type
	24, // [24:33] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_repository_v1_repository_proto_init() }
func file_repository_v1_repository_proto_init() {
	if File_repository_v1_repository_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_v1_repository_proto_rawDesc), len(file_repository_v1_repository_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_v1_repository_proto_goTypes,
		DependencyIndexes: file_repository_v1_repository_proto_depIdxs,
		MessageInfos:      file_repository_v1_repository_proto_msgTypes,
	}.Build()
	File_repository_v1_repository_proto = out.File
	file_repository_v1_repository_proto_goTypes = nil
	file_repository_v1_repository_proto_depIdxs = nil
}
