// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ranking/events/v1/ranking_events.proto

package rankingeventsv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RankingEventEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RankingEventEnvelope) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RankingEventEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RankingEventEnvelopeMultiError, or nil if none found.
func (m *RankingEventEnvelope) ValidateAll() error {
	return m.validate(true)
}

func (m *RankingEventEnvelope) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetEventId()); l < 1 || l > 128 {
		err := RankingEventEnvelopeValidationError{
			field:  "EventId",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for EventType

	if m.GetOccurredAt() == nil {
		err := RankingEventEnvelopeValidationError{
			field:  "OccurredAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	switch v := m.Payload.(type) {
	case *RankingEventEnvelope_UserFollowed:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetUserFollowed()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "UserFollowed",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "UserFollowed",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUserFollowed()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "UserFollowed",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_UserUnfollowed:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetUserUnfollowed()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "UserUnfollowed",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "UserUnfollowed",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUserUnfollowed()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "UserUnfollowed",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_RepositoryCreated:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRepositoryCreated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRepositoryCreated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "RepositoryCreated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_RepositoryVisibilityChanged:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRepositoryVisibilityChanged()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryVisibilityChanged",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryVisibilityChanged",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRepositoryVisibilityChanged()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "RepositoryVisibilityChanged",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_RepositoryStarred:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRepositoryStarred()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryStarred",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryStarred",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRepositoryStarred()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "RepositoryStarred",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_RepositoryUnstarred:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRepositoryUnstarred()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryUnstarred",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryUnstarred",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRepositoryUnstarred()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "RepositoryUnstarred",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_RepositoryForked:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRepositoryForked()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryForked",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "RepositoryForked",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRepositoryForked()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "RepositoryForked",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_DocumentCreated:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetDocumentCreated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "DocumentCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "DocumentCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDocumentCreated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "DocumentCreated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_DocumentVersionCreated:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetDocumentVersionCreated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "DocumentVersionCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "DocumentVersionCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDocumentVersionCreated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "DocumentVersionCreated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_FileCreated:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFileCreated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "FileCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "FileCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFileCreated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "FileCreated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RankingEventEnvelope_FileVersionCreated:
		if v == nil {
			err := RankingEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFileVersionCreated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "FileVersionCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RankingEventEnvelopeValidationError{
						field:  "FileVersionCreated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFileVersionCreated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RankingEventEnvelopeValidationError{
					field:  "FileVersionCreated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return RankingEventEnvelopeMultiError(errors)
	}

	return nil
}

// RankingEventEnvelopeMultiError is an error wrapping multiple validation
// errors returned by RankingEventEnvelope.ValidateAll() if the designated
// constraints aren't met.
type RankingEventEnvelopeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RankingEventEnvelopeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RankingEventEnvelopeMultiError) AllErrors() []error { return m }

// RankingEventEnvelopeValidationError is the validation error returned by
// RankingEventEnvelope.Validate if the designated constraints aren't met.
type RankingEventEnvelopeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RankingEventEnvelopeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RankingEventEnvelopeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RankingEventEnvelopeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RankingEventEnvelopeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RankingEventEnvelopeValidationError) ErrorName() string {
	return "RankingEventEnvelopeValidationError"
}

// Error satisfies the builtin error interface
func (e RankingEventEnvelopeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRankingEventEnvelope.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RankingEventEnvelopeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RankingEventEnvelopeValidationError{}

// Validate checks the field values on UserFollowed with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserFollowed) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserFollowed with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserFollowedMultiError, or
// nil if none found.
func (m *UserFollowed) ValidateAll() error {
	return m.validate(true)
}

func (m *UserFollowed) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() == nil {
		err := UserFollowedValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserFollowedValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserFollowedValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserFollowedValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Delta

	if len(errors) > 0 {
		return UserFollowedMultiError(errors)
	}

	return nil
}

// UserFollowedMultiError is an error wrapping multiple validation errors
// returned by UserFollowed.ValidateAll() if the designated constraints aren't met.
type UserFollowedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserFollowedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserFollowedMultiError) AllErrors() []error { return m }

// UserFollowedValidationError is the validation error returned by
// UserFollowed.Validate if the designated constraints aren't met.
type UserFollowedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserFollowedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserFollowedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserFollowedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserFollowedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserFollowedValidationError) ErrorName() string { return "UserFollowedValidationError" }

// Error satisfies the builtin error interface
func (e UserFollowedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserFollowed.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserFollowedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserFollowedValidationError{}

// Validate checks the field values on UserUnfollowed with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserUnfollowed) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserUnfollowed with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserUnfollowedMultiError,
// or nil if none found.
func (m *UserUnfollowed) ValidateAll() error {
	return m.validate(true)
}

func (m *UserUnfollowed) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() == nil {
		err := UserUnfollowedValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserUnfollowedValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserUnfollowedValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserUnfollowedValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Delta

	if len(errors) > 0 {
		return UserUnfollowedMultiError(errors)
	}

	return nil
}

// UserUnfollowedMultiError is an error wrapping multiple validation errors
// returned by UserUnfollowed.ValidateAll() if the designated constraints
// aren't met.
type UserUnfollowedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserUnfollowedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserUnfollowedMultiError) AllErrors() []error { return m }

// UserUnfollowedValidationError is the validation error returned by
// UserUnfollowed.Validate if the designated constraints aren't met.
type UserUnfollowedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserUnfollowedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserUnfollowedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserUnfollowedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserUnfollowedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserUnfollowedValidationError) ErrorName() string { return "UserUnfollowedValidationError" }

// Error satisfies the builtin error interface
func (e UserUnfollowedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserUnfollowed.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserUnfollowedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserUnfollowedValidationError{}

// Validate checks the field values on RepositoryCreated with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RepositoryCreated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RepositoryCreated with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RepositoryCreatedMultiError, or nil if none found.
func (m *RepositoryCreated) ValidateAll() error {
	return m.validate(true)
}

func (m *RepositoryCreated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() == nil {
		err := RepositoryCreatedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryCreatedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := RepositoryCreatedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryCreatedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := RepositoryCreatedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryCreatedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for IsPublic

	if len(errors) > 0 {
		return RepositoryCreatedMultiError(errors)
	}

	return nil
}

// RepositoryCreatedMultiError is an error wrapping multiple validation errors
// returned by RepositoryCreated.ValidateAll() if the designated constraints
// aren't met.
type RepositoryCreatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RepositoryCreatedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RepositoryCreatedMultiError) AllErrors() []error { return m }

// RepositoryCreatedValidationError is the validation error returned by
// RepositoryCreated.Validate if the designated constraints aren't met.
type RepositoryCreatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RepositoryCreatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RepositoryCreatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RepositoryCreatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RepositoryCreatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RepositoryCreatedValidationError) ErrorName() string {
	return "RepositoryCreatedValidationError"
}

// Error satisfies the builtin error interface
func (e RepositoryCreatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRepositoryCreated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RepositoryCreatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RepositoryCreatedValidationError{}

// Validate checks the field values on RepositoryVisibilityChanged with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RepositoryVisibilityChanged) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RepositoryVisibilityChanged with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RepositoryVisibilityChangedMultiError, or nil if none found.
func (m *RepositoryVisibilityChanged) ValidateAll() error {
	return m.validate(true)
}

func (m *RepositoryVisibilityChanged) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() == nil {
		err := RepositoryVisibilityChangedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryVisibilityChangedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryVisibilityChangedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryVisibilityChangedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := RepositoryVisibilityChangedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryVisibilityChangedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryVisibilityChangedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryVisibilityChangedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := RepositoryVisibilityChangedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryVisibilityChangedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryVisibilityChangedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryVisibilityChangedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for IsPublic

	// no validation rules for Delta

	if len(errors) > 0 {
		return RepositoryVisibilityChangedMultiError(errors)
	}

	return nil
}

// RepositoryVisibilityChangedMultiError is an error wrapping multiple
// validation errors returned by RepositoryVisibilityChanged.ValidateAll() if
// the designated constraints aren't met.
type RepositoryVisibilityChangedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RepositoryVisibilityChangedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RepositoryVisibilityChangedMultiError) AllErrors() []error { return m }

// RepositoryVisibilityChangedValidationError is the validation error returned
// by RepositoryVisibilityChanged.Validate if the designated constraints
// aren't met.
type RepositoryVisibilityChangedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RepositoryVisibilityChangedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RepositoryVisibilityChangedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RepositoryVisibilityChangedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RepositoryVisibilityChangedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RepositoryVisibilityChangedValidationError) ErrorName() string {
	return "RepositoryVisibilityChangedValidationError"
}

// Error satisfies the builtin error interface
func (e RepositoryVisibilityChangedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRepositoryVisibilityChanged.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RepositoryVisibilityChangedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RepositoryVisibilityChangedValidationError{}

// Validate checks the field values on RepositoryStarred with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RepositoryStarred) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RepositoryStarred with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RepositoryStarredMultiError, or nil if none found.
func (m *RepositoryStarred) ValidateAll() error {
	return m.validate(true)
}

func (m *RepositoryStarred) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() == nil {
		err := RepositoryStarredValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryStarredValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryStarredValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryStarredValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := RepositoryStarredValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryStarredValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryStarredValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryStarredValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := RepositoryStarredValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryStarredValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryStarredValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryStarredValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Delta

	if len(errors) > 0 {
		return RepositoryStarredMultiError(errors)
	}

	return nil
}

// RepositoryStarredMultiError is an error wrapping multiple validation errors
// returned by RepositoryStarred.ValidateAll() if the designated constraints
// aren't met.
type RepositoryStarredMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RepositoryStarredMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RepositoryStarredMultiError) AllErrors() []error { return m }

// RepositoryStarredValidationError is the validation error returned by
// RepositoryStarred.Validate if the designated constraints aren't met.
type RepositoryStarredValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RepositoryStarredValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RepositoryStarredValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RepositoryStarredValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RepositoryStarredValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RepositoryStarredValidationError) ErrorName() string {
	return "RepositoryStarredValidationError"
}

// Error satisfies the builtin error interface
func (e RepositoryStarredValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRepositoryStarred.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RepositoryStarredValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RepositoryStarredValidationError{}

// Validate checks the field values on RepositoryUnstarred with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RepositoryUnstarred) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RepositoryUnstarred with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RepositoryUnstarredMultiError, or nil if none found.
func (m *RepositoryUnstarred) ValidateAll() error {
	return m.validate(true)
}

func (m *RepositoryUnstarred) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() == nil {
		err := RepositoryUnstarredValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryUnstarredValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryUnstarredValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryUnstarredValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := RepositoryUnstarredValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryUnstarredValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryUnstarredValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryUnstarredValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := RepositoryUnstarredValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryUnstarredValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryUnstarredValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryUnstarredValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Delta

	if len(errors) > 0 {
		return RepositoryUnstarredMultiError(errors)
	}

	return nil
}

// RepositoryUnstarredMultiError is an error wrapping multiple validation
// errors returned by RepositoryUnstarred.ValidateAll() if the designated
// constraints aren't met.
type RepositoryUnstarredMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RepositoryUnstarredMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RepositoryUnstarredMultiError) AllErrors() []error { return m }

// RepositoryUnstarredValidationError is the validation error returned by
// RepositoryUnstarred.Validate if the designated constraints aren't met.
type RepositoryUnstarredValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RepositoryUnstarredValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RepositoryUnstarredValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RepositoryUnstarredValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RepositoryUnstarredValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RepositoryUnstarredValidationError) ErrorName() string {
	return "RepositoryUnstarredValidationError"
}

// Error satisfies the builtin error interface
func (e RepositoryUnstarredValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRepositoryUnstarred.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RepositoryUnstarredValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RepositoryUnstarredValidationError{}

// Validate checks the field values on RepositoryForked with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RepositoryForked) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RepositoryForked with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RepositoryForkedMultiError, or nil if none found.
func (m *RepositoryForked) ValidateAll() error {
	return m.validate(true)
}

func (m *RepositoryForked) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() == nil {
		err := RepositoryForkedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryForkedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryForkedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryForkedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := RepositoryForkedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryForkedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryForkedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryForkedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := RepositoryForkedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryForkedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryForkedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryForkedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Delta

	if len(errors) > 0 {
		return RepositoryForkedMultiError(errors)
	}

	return nil
}

// RepositoryForkedMultiError is an error wrapping multiple validation errors
// returned by RepositoryForked.ValidateAll() if the designated constraints
// aren't met.
type RepositoryForkedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RepositoryForkedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RepositoryForkedMultiError) AllErrors() []error { return m }

// RepositoryForkedValidationError is the validation error returned by
// RepositoryForked.Validate if the designated constraints aren't met.
type RepositoryForkedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RepositoryForkedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RepositoryForkedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RepositoryForkedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RepositoryForkedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RepositoryForkedValidationError) ErrorName() string { return "RepositoryForkedValidationError" }

// Error satisfies the builtin error interface
func (e RepositoryForkedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRepositoryForked.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RepositoryForkedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RepositoryForkedValidationError{}

// Validate checks the field values on DocumentCreated with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DocumentCreated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DocumentCreated with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DocumentCreatedMultiError, or nil if none found.
func (m *DocumentCreated) ValidateAll() error {
	return m.validate(true)
}

func (m *DocumentCreated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() == nil {
		err := DocumentCreatedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentCreatedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := DocumentCreatedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentCreatedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := DocumentCreatedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentCreatedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DocumentCreatedMultiError(errors)
	}

	return nil
}

// DocumentCreatedMultiError is an error wrapping multiple validation errors
// returned by DocumentCreated.ValidateAll() if the designated constraints
// aren't met.
type DocumentCreatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentCreatedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentCreatedMultiError) AllErrors() []error { return m }

// DocumentCreatedValidationError is the validation error returned by
// DocumentCreated.Validate if the designated constraints aren't met.
type DocumentCreatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentCreatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentCreatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentCreatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentCreatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentCreatedValidationError) ErrorName() string { return "DocumentCreatedValidationError" }

// Error satisfies the builtin error interface
func (e DocumentCreatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocumentCreated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentCreatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentCreatedValidationError{}

// Validate checks the field values on DocumentVersionCreated with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DocumentVersionCreated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DocumentVersionCreated with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DocumentVersionCreatedMultiError, or nil if none found.
func (m *DocumentVersionCreated) ValidateAll() error {
	return m.validate(true)
}

func (m *DocumentVersionCreated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() == nil {
		err := DocumentVersionCreatedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentVersionCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentVersionCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentVersionCreatedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := DocumentVersionCreatedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentVersionCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentVersionCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentVersionCreatedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := DocumentVersionCreatedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentVersionCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentVersionCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentVersionCreatedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DocumentVersionCreatedMultiError(errors)
	}

	return nil
}

// DocumentVersionCreatedMultiError is an error wrapping multiple validation
// errors returned by DocumentVersionCreated.ValidateAll() if the designated
// constraints aren't met.
type DocumentVersionCreatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentVersionCreatedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentVersionCreatedMultiError) AllErrors() []error { return m }

// DocumentVersionCreatedValidationError is the validation error returned by
// DocumentVersionCreated.Validate if the designated constraints aren't met.
type DocumentVersionCreatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentVersionCreatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentVersionCreatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentVersionCreatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentVersionCreatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentVersionCreatedValidationError) ErrorName() string {
	return "DocumentVersionCreatedValidationError"
}

// Error satisfies the builtin error interface
func (e DocumentVersionCreatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocumentVersionCreated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentVersionCreatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentVersionCreatedValidationError{}

// Validate checks the field values on FileCreated with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FileCreated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileCreated with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FileCreatedMultiError, or
// nil if none found.
func (m *FileCreated) ValidateAll() error {
	return m.validate(true)
}

func (m *FileCreated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() == nil {
		err := FileCreatedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileCreatedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := FileCreatedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileCreatedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := FileCreatedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileCreatedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FileCreatedMultiError(errors)
	}

	return nil
}

// FileCreatedMultiError is an error wrapping multiple validation errors
// returned by FileCreated.ValidateAll() if the designated constraints aren't met.
type FileCreatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileCreatedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileCreatedMultiError) AllErrors() []error { return m }

// FileCreatedValidationError is the validation error returned by
// FileCreated.Validate if the designated constraints aren't met.
type FileCreatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileCreatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileCreatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileCreatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileCreatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileCreatedValidationError) ErrorName() string { return "FileCreatedValidationError" }

// Error satisfies the builtin error interface
func (e FileCreatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileCreated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileCreatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileCreatedValidationError{}

// Validate checks the field values on FileVersionCreated with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FileVersionCreated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileVersionCreated with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FileVersionCreatedMultiError, or nil if none found.
func (m *FileVersionCreated) ValidateAll() error {
	return m.validate(true)
}

func (m *FileVersionCreated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOwnerId() == nil {
		err := FileVersionCreatedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileVersionCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileVersionCreatedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileVersionCreatedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := FileVersionCreatedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileVersionCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileVersionCreatedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileVersionCreatedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := FileVersionCreatedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileVersionCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileVersionCreatedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileVersionCreatedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FileVersionCreatedMultiError(errors)
	}

	return nil
}

// FileVersionCreatedMultiError is an error wrapping multiple validation errors
// returned by FileVersionCreated.ValidateAll() if the designated constraints
// aren't met.
type FileVersionCreatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileVersionCreatedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileVersionCreatedMultiError) AllErrors() []error { return m }

// FileVersionCreatedValidationError is the validation error returned by
// FileVersionCreated.Validate if the designated constraints aren't met.
type FileVersionCreatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileVersionCreatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileVersionCreatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileVersionCreatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileVersionCreatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileVersionCreatedValidationError) ErrorName() string {
	return "FileVersionCreatedValidationError"
}

// Error satisfies the builtin error interface
func (e FileVersionCreatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileVersionCreated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileVersionCreatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileVersionCreatedValidationError{}
