// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: profile/v1/profile.proto

package profilev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProfileTitle with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProfileTitle) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProfileTitle with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProfileTitleMultiError, or
// nil if none found.
func (m *ProfileTitle) ValidateAll() error {
	return m.validate(true)
}

func (m *ProfileTitle) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetCode()); l < 1 || l > 64 {
		err := ProfileTitleValidationError{
			field:  "Code",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetLabel()); l < 1 || l > 100 {
		err := ProfileTitleValidationError{
			field:  "Label",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) > 500 {
		err := ProfileTitleValidationError{
			field:  "Description",
			reason: "value length must be at most 500 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for SortOrder

	// no validation rules for IsActive

	// no validation rules for IsSystem

	if len(errors) > 0 {
		return ProfileTitleMultiError(errors)
	}

	return nil
}

// ProfileTitleMultiError is an error wrapping multiple validation errors
// returned by ProfileTitle.ValidateAll() if the designated constraints aren't met.
type ProfileTitleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProfileTitleMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProfileTitleMultiError) AllErrors() []error { return m }

// ProfileTitleValidationError is the validation error returned by
// ProfileTitle.Validate if the designated constraints aren't met.
type ProfileTitleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProfileTitleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProfileTitleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProfileTitleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProfileTitleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProfileTitleValidationError) ErrorName() string { return "ProfileTitleValidationError" }

// Error satisfies the builtin error interface
func (e ProfileTitleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProfileTitle.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProfileTitleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProfileTitleValidationError{}

// Validate checks the field values on ProfileSocialLink with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProfileSocialLink) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProfileSocialLink with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProfileSocialLinkMultiError, or nil if none found.
func (m *ProfileSocialLink) ValidateAll() error {
	return m.validate(true)
}

func (m *ProfileSocialLink) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSocialLinkId() == nil {
		err := ProfileSocialLinkValidationError{
			field:  "SocialLinkId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetSocialLinkId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProfileSocialLinkValidationError{
					field:  "SocialLinkId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProfileSocialLinkValidationError{
					field:  "SocialLinkId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSocialLinkId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProfileSocialLinkValidationError{
				field:  "SocialLinkId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetUserId() == nil {
		err := ProfileSocialLinkValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProfileSocialLinkValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProfileSocialLinkValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProfileSocialLinkValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Platform

	if l := utf8.RuneCountInString(m.GetUrl()); l < 1 || l > 2048 {
		err := ProfileSocialLinkValidationError{
			field:  "Url",
			reason: "value length must be between 1 and 2048 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetLabel()) > 64 {
		err := ProfileSocialLinkValidationError{
			field:  "Label",
			reason: "value length must be at most 64 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Position

	// no validation rules for IsVisible

	if m.GetCreatedAt() == nil {
		err := ProfileSocialLinkValidationError{
			field:  "CreatedAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProfileSocialLinkValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProfileSocialLinkValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProfileSocialLinkValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ProfileSocialLinkMultiError(errors)
	}

	return nil
}

// ProfileSocialLinkMultiError is an error wrapping multiple validation errors
// returned by ProfileSocialLink.ValidateAll() if the designated constraints
// aren't met.
type ProfileSocialLinkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProfileSocialLinkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProfileSocialLinkMultiError) AllErrors() []error { return m }

// ProfileSocialLinkValidationError is the validation error returned by
// ProfileSocialLink.Validate if the designated constraints aren't met.
type ProfileSocialLinkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProfileSocialLinkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProfileSocialLinkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProfileSocialLinkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProfileSocialLinkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProfileSocialLinkValidationError) ErrorName() string {
	return "ProfileSocialLinkValidationError"
}

// Error satisfies the builtin error interface
func (e ProfileSocialLinkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProfileSocialLink.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProfileSocialLinkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProfileSocialLinkValidationError{}

// Validate checks the field values on Profile with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Profile) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Profile with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ProfileMultiError, or nil if none found.
func (m *Profile) ValidateAll() error {
	return m.validate(true)
}

func (m *Profile) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() == nil {
		err := ProfileValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProfileValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProfileValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProfileValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetUsername()); l < 3 || l > 32 {
		err := ProfileValidationError{
			field:  "Username",
			reason: "value length must be between 3 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_Profile_Username_Pattern.MatchString(m.GetUsername()) {
		err := ProfileValidationError{
			field:  "Username",
			reason: "value does not match regex pattern \"^[a-z0-9](?:[a-z0-9._-]{1,30}[a-z0-9])?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDisplayName()) > 100 {
		err := ProfileValidationError{
			field:  "DisplayName",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBio()) > 1000 {
		err := ProfileValidationError{
			field:  "Bio",
			reason: "value length must be at most 1000 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAvatarUrl()) > 2048 {
		err := ProfileValidationError{
			field:  "AvatarUrl",
			reason: "value length must be at most 2048 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCoverUrl()) > 2048 {
		err := ProfileValidationError{
			field:  "CoverUrl",
			reason: "value length must be at most 2048 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetLocation()) > 100 {
		err := ProfileValidationError{
			field:  "Location",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetWebsiteUrl()) > 2048 {
		err := ProfileValidationError{
			field:  "WebsiteUrl",
			reason: "value length must be at most 2048 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ReadmeMarkdown

	// no validation rules for IsPublic

	if all {
		switch v := interface{}(m.GetTitle()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProfileValidationError{
					field:  "Title",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProfileValidationError{
					field:  "Title",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTitle()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProfileValidationError{
				field:  "Title",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TitleSource

	// no validation rules for FollowersCount

	// no validation rules for FollowingCount

	for idx, item := range m.GetSocialLinks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProfileValidationError{
						field:  fmt.Sprintf("SocialLinks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProfileValidationError{
						field:  fmt.Sprintf("SocialLinks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProfileValidationError{
					field:  fmt.Sprintf("SocialLinks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.GetCreatedAt() == nil {
		err := ProfileValidationError{
			field:  "CreatedAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProfileValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProfileValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProfileValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ProfileMultiError(errors)
	}

	return nil
}

// ProfileMultiError is an error wrapping multiple validation errors returned
// by Profile.ValidateAll() if the designated constraints aren't met.
type ProfileMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProfileMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProfileMultiError) AllErrors() []error { return m }

// ProfileValidationError is the validation error returned by Profile.Validate
// if the designated constraints aren't met.
type ProfileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProfileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProfileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProfileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProfileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProfileValidationError) ErrorName() string { return "ProfileValidationError" }

// Error satisfies the builtin error interface
func (e ProfileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProfile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProfileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProfileValidationError{}

var _Profile_Username_Pattern = regexp.MustCompile("^[a-z0-9](?:[a-z0-9._-]{1,30}[a-z0-9])?$")

// Validate checks the field values on ProfilePreview with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProfilePreview) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProfilePreview with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProfilePreviewMultiError,
// or nil if none found.
func (m *ProfilePreview) ValidateAll() error {
	return m.validate(true)
}

func (m *ProfilePreview) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() == nil {
		err := ProfilePreviewValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProfilePreviewValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProfilePreviewValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProfilePreviewValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetUsername()); l < 3 || l > 32 {
		err := ProfilePreviewValidationError{
			field:  "Username",
			reason: "value length must be between 3 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDisplayName()) > 100 {
		err := ProfilePreviewValidationError{
			field:  "DisplayName",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAvatarUrl()) > 2048 {
		err := ProfilePreviewValidationError{
			field:  "AvatarUrl",
			reason: "value length must be at most 2048 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTitle()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProfilePreviewValidationError{
					field:  "Title",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProfilePreviewValidationError{
					field:  "Title",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTitle()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProfilePreviewValidationError{
				field:  "Title",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ProfilePreviewMultiError(errors)
	}

	return nil
}

// ProfilePreviewMultiError is an error wrapping multiple validation errors
// returned by ProfilePreview.ValidateAll() if the designated constraints
// aren't met.
type ProfilePreviewMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProfilePreviewMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProfilePreviewMultiError) AllErrors() []error { return m }

// ProfilePreviewValidationError is the validation error returned by
// ProfilePreview.Validate if the designated constraints aren't met.
type ProfilePreviewValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProfilePreviewValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProfilePreviewValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProfilePreviewValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProfilePreviewValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProfilePreviewValidationError) ErrorName() string { return "ProfilePreviewValidationError" }

// Error satisfies the builtin error interface
func (e ProfilePreviewValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProfilePreview.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProfilePreviewValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProfilePreviewValidationError{}

// Validate checks the field values on GetProfileByUserIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProfileByUserIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProfileByUserIdRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProfileByUserIdRequestMultiError, or nil if none found.
func (m *GetProfileByUserIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProfileByUserIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() == nil {
		err := GetProfileByUserIdRequestValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetProfileByUserIdRequestValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetProfileByUserIdRequestValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetProfileByUserIdRequestValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetProfileByUserIdRequestMultiError(errors)
	}

	return nil
}

// GetProfileByUserIdRequestMultiError is an error wrapping multiple validation
// errors returned by GetProfileByUserIdRequest.ValidateAll() if the
// designated constraints aren't met.
type GetProfileByUserIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProfileByUserIdRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProfileByUserIdRequestMultiError) AllErrors() []error { return m }

// GetProfileByUserIdRequestValidationError is the validation error returned by
// GetProfileByUserIdRequest.Validate if the designated constraints aren't met.
type GetProfileByUserIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProfileByUserIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProfileByUserIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProfileByUserIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProfileByUserIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProfileByUserIdRequestValidationError) ErrorName() string {
	return "GetProfileByUserIdRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetProfileByUserIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProfileByUserIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProfileByUserIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProfileByUserIdRequestValidationError{}

// Validate checks the field values on GetProfileByUsernameRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProfileByUsernameRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProfileByUsernameRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProfileByUsernameRequestMultiError, or nil if none found.
func (m *GetProfileByUsernameRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProfileByUsernameRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUsername()); l < 3 || l > 32 {
		err := GetProfileByUsernameRequestValidationError{
			field:  "Username",
			reason: "value length must be between 3 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_GetProfileByUsernameRequest_Username_Pattern.MatchString(m.GetUsername()) {
		err := GetProfileByUsernameRequestValidationError{
			field:  "Username",
			reason: "value does not match regex pattern \"^[a-z0-9](?:[a-z0-9._-]{1,30}[a-z0-9])?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetProfileByUsernameRequestMultiError(errors)
	}

	return nil
}

// GetProfileByUsernameRequestMultiError is an error wrapping multiple
// validation errors returned by GetProfileByUsernameRequest.ValidateAll() if
// the designated constraints aren't met.
type GetProfileByUsernameRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProfileByUsernameRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProfileByUsernameRequestMultiError) AllErrors() []error { return m }

// GetProfileByUsernameRequestValidationError is the validation error returned
// by GetProfileByUsernameRequest.Validate if the designated constraints
// aren't met.
type GetProfileByUsernameRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProfileByUsernameRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProfileByUsernameRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProfileByUsernameRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProfileByUsernameRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProfileByUsernameRequestValidationError) ErrorName() string {
	return "GetProfileByUsernameRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetProfileByUsernameRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProfileByUsernameRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProfileByUsernameRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProfileByUsernameRequestValidationError{}

var _GetProfileByUsernameRequest_Username_Pattern = regexp.MustCompile("^[a-z0-9](?:[a-z0-9._-]{1,30}[a-z0-9])?$")

// Validate checks the field values on GetProfileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProfileResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProfileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProfileResponseMultiError, or nil if none found.
func (m *GetProfileResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProfileResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProfile()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetProfileResponseValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetProfileResponseValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProfile()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetProfileResponseValidationError{
				field:  "Profile",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetProfileResponseMultiError(errors)
	}

	return nil
}

// GetProfileResponseMultiError is an error wrapping multiple validation errors
// returned by GetProfileResponse.ValidateAll() if the designated constraints
// aren't met.
type GetProfileResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProfileResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProfileResponseMultiError) AllErrors() []error { return m }

// GetProfileResponseValidationError is the validation error returned by
// GetProfileResponse.Validate if the designated constraints aren't met.
type GetProfileResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProfileResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProfileResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProfileResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProfileResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProfileResponseValidationError) ErrorName() string {
	return "GetProfileResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetProfileResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProfileResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProfileResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProfileResponseValidationError{}

// Validate checks the field values on UpdateProfileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateProfileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateProfileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateProfileRequestMultiError, or nil if none found.
func (m *UpdateProfileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateProfileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDisplayName()) > 100 {
		err := UpdateProfileRequestValidationError{
			field:  "DisplayName",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBio()) > 1000 {
		err := UpdateProfileRequestValidationError{
			field:  "Bio",
			reason: "value length must be at most 1000 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAvatarUrl()) > 2048 {
		err := UpdateProfileRequestValidationError{
			field:  "AvatarUrl",
			reason: "value length must be at most 2048 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCoverUrl()) > 2048 {
		err := UpdateProfileRequestValidationError{
			field:  "CoverUrl",
			reason: "value length must be at most 2048 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetLocation()) > 100 {
		err := UpdateProfileRequestValidationError{
			field:  "Location",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetWebsiteUrl()) > 2048 {
		err := UpdateProfileRequestValidationError{
			field:  "WebsiteUrl",
			reason: "value length must be at most 2048 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsPublic

	if len(errors) > 0 {
		return UpdateProfileRequestMultiError(errors)
	}

	return nil
}

// UpdateProfileRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateProfileRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateProfileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateProfileRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateProfileRequestMultiError) AllErrors() []error { return m }

// UpdateProfileRequestValidationError is the validation error returned by
// UpdateProfileRequest.Validate if the designated constraints aren't met.
type UpdateProfileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateProfileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateProfileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateProfileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateProfileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateProfileRequestValidationError) ErrorName() string {
	return "UpdateProfileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateProfileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateProfileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateProfileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateProfileRequestValidationError{}

// Validate checks the field values on UpdateProfileReadmeRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateProfileReadmeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateProfileReadmeRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateProfileReadmeRequestMultiError, or nil if none found.
func (m *UpdateProfileReadmeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateProfileReadmeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReadmeMarkdown

	if len(errors) > 0 {
		return UpdateProfileReadmeRequestMultiError(errors)
	}

	return nil
}

// UpdateProfileReadmeRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateProfileReadmeRequest.ValidateAll() if
// the designated constraints aren't met.
type UpdateProfileReadmeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateProfileReadmeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateProfileReadmeRequestMultiError) AllErrors() []error { return m }

// UpdateProfileReadmeRequestValidationError is the validation error returned
// by UpdateProfileReadmeRequest.Validate if the designated constraints aren't met.
type UpdateProfileReadmeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateProfileReadmeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateProfileReadmeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateProfileReadmeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateProfileReadmeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateProfileReadmeRequestValidationError) ErrorName() string {
	return "UpdateProfileReadmeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateProfileReadmeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateProfileReadmeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateProfileReadmeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateProfileReadmeRequestValidationError{}

// Validate checks the field values on UpdateProfileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateProfileResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateProfileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateProfileResponseMultiError, or nil if none found.
func (m *UpdateProfileResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateProfileResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProfile()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateProfileResponseValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateProfileResponseValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProfile()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateProfileResponseValidationError{
				field:  "Profile",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateProfileResponseMultiError(errors)
	}

	return nil
}

// UpdateProfileResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateProfileResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateProfileResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateProfileResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateProfileResponseMultiError) AllErrors() []error { return m }

// UpdateProfileResponseValidationError is the validation error returned by
// UpdateProfileResponse.Validate if the designated constraints aren't met.
type UpdateProfileResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateProfileResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateProfileResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateProfileResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateProfileResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateProfileResponseValidationError) ErrorName() string {
	return "UpdateProfileResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateProfileResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateProfileResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateProfileResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateProfileResponseValidationError{}

// Validate checks the field values on ListProfileSocialLinksRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListProfileSocialLinksRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProfileSocialLinksRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListProfileSocialLinksRequestMultiError, or nil if none found.
func (m *ListProfileSocialLinksRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProfileSocialLinksRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() == nil {
		err := ListProfileSocialLinksRequestValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListProfileSocialLinksRequestValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListProfileSocialLinksRequestValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListProfileSocialLinksRequestValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListProfileSocialLinksRequestMultiError(errors)
	}

	return nil
}

// ListProfileSocialLinksRequestMultiError is an error wrapping multiple
// validation errors returned by ListProfileSocialLinksRequest.ValidateAll()
// if the designated constraints aren't met.
type ListProfileSocialLinksRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProfileSocialLinksRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProfileSocialLinksRequestMultiError) AllErrors() []error { return m }

// ListProfileSocialLinksRequestValidationError is the validation error
// returned by ListProfileSocialLinksRequest.Validate if the designated
// constraints aren't met.
type ListProfileSocialLinksRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProfileSocialLinksRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProfileSocialLinksRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProfileSocialLinksRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProfileSocialLinksRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProfileSocialLinksRequestValidationError) ErrorName() string {
	return "ListProfileSocialLinksRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListProfileSocialLinksRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProfileSocialLinksRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProfileSocialLinksRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProfileSocialLinksRequestValidationError{}

// Validate checks the field values on ListProfileSocialLinksResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListProfileSocialLinksResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProfileSocialLinksResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListProfileSocialLinksResponseMultiError, or nil if none found.
func (m *ListProfileSocialLinksResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProfileSocialLinksResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSocialLinks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListProfileSocialLinksResponseValidationError{
						field:  fmt.Sprintf("SocialLinks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListProfileSocialLinksResponseValidationError{
						field:  fmt.Sprintf("SocialLinks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListProfileSocialLinksResponseValidationError{
					field:  fmt.Sprintf("SocialLinks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListProfileSocialLinksResponseMultiError(errors)
	}

	return nil
}

// ListProfileSocialLinksResponseMultiError is an error wrapping multiple
// validation errors returned by ListProfileSocialLinksResponse.ValidateAll()
// if the designated constraints aren't met.
type ListProfileSocialLinksResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProfileSocialLinksResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProfileSocialLinksResponseMultiError) AllErrors() []error { return m }

// ListProfileSocialLinksResponseValidationError is the validation error
// returned by ListProfileSocialLinksResponse.Validate if the designated
// constraints aren't met.
type ListProfileSocialLinksResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProfileSocialLinksResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProfileSocialLinksResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProfileSocialLinksResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProfileSocialLinksResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProfileSocialLinksResponseValidationError) ErrorName() string {
	return "ListProfileSocialLinksResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListProfileSocialLinksResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProfileSocialLinksResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProfileSocialLinksResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProfileSocialLinksResponseValidationError{}

// Validate checks the field values on UpsertProfileSocialLinkRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertProfileSocialLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertProfileSocialLinkRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpsertProfileSocialLinkRequestMultiError, or nil if none found.
func (m *UpsertProfileSocialLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertProfileSocialLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSocialLinkId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpsertProfileSocialLinkRequestValidationError{
					field:  "SocialLinkId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpsertProfileSocialLinkRequestValidationError{
					field:  "SocialLinkId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSocialLinkId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpsertProfileSocialLinkRequestValidationError{
				field:  "SocialLinkId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Platform

	if l := utf8.RuneCountInString(m.GetUrl()); l < 1 || l > 2048 {
		err := UpsertProfileSocialLinkRequestValidationError{
			field:  "Url",
			reason: "value length must be between 1 and 2048 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetLabel()) > 64 {
		err := UpsertProfileSocialLinkRequestValidationError{
			field:  "Label",
			reason: "value length must be at most 64 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Position

	// no validation rules for IsVisible

	if len(errors) > 0 {
		return UpsertProfileSocialLinkRequestMultiError(errors)
	}

	return nil
}

// UpsertProfileSocialLinkRequestMultiError is an error wrapping multiple
// validation errors returned by UpsertProfileSocialLinkRequest.ValidateAll()
// if the designated constraints aren't met.
type UpsertProfileSocialLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertProfileSocialLinkRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertProfileSocialLinkRequestMultiError) AllErrors() []error { return m }

// UpsertProfileSocialLinkRequestValidationError is the validation error
// returned by UpsertProfileSocialLinkRequest.Validate if the designated
// constraints aren't met.
type UpsertProfileSocialLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertProfileSocialLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertProfileSocialLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertProfileSocialLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertProfileSocialLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertProfileSocialLinkRequestValidationError) ErrorName() string {
	return "UpsertProfileSocialLinkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertProfileSocialLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertProfileSocialLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertProfileSocialLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertProfileSocialLinkRequestValidationError{}

// Validate checks the field values on UpsertProfileSocialLinkResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertProfileSocialLinkResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertProfileSocialLinkResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpsertProfileSocialLinkResponseMultiError, or nil if none found.
func (m *UpsertProfileSocialLinkResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertProfileSocialLinkResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSocialLink()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpsertProfileSocialLinkResponseValidationError{
					field:  "SocialLink",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpsertProfileSocialLinkResponseValidationError{
					field:  "SocialLink",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSocialLink()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpsertProfileSocialLinkResponseValidationError{
				field:  "SocialLink",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpsertProfileSocialLinkResponseMultiError(errors)
	}

	return nil
}

// UpsertProfileSocialLinkResponseMultiError is an error wrapping multiple
// validation errors returned by UpsertProfileSocialLinkResponse.ValidateAll()
// if the designated constraints aren't met.
type UpsertProfileSocialLinkResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertProfileSocialLinkResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertProfileSocialLinkResponseMultiError) AllErrors() []error { return m }

// UpsertProfileSocialLinkResponseValidationError is the validation error
// returned by UpsertProfileSocialLinkResponse.Validate if the designated
// constraints aren't met.
type UpsertProfileSocialLinkResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertProfileSocialLinkResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertProfileSocialLinkResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertProfileSocialLinkResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertProfileSocialLinkResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertProfileSocialLinkResponseValidationError) ErrorName() string {
	return "UpsertProfileSocialLinkResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertProfileSocialLinkResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertProfileSocialLinkResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertProfileSocialLinkResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertProfileSocialLinkResponseValidationError{}

// Validate checks the field values on DeleteProfileSocialLinkRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteProfileSocialLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteProfileSocialLinkRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteProfileSocialLinkRequestMultiError, or nil if none found.
func (m *DeleteProfileSocialLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteProfileSocialLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSocialLinkId() == nil {
		err := DeleteProfileSocialLinkRequestValidationError{
			field:  "SocialLinkId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetSocialLinkId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteProfileSocialLinkRequestValidationError{
					field:  "SocialLinkId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteProfileSocialLinkRequestValidationError{
					field:  "SocialLinkId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSocialLinkId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteProfileSocialLinkRequestValidationError{
				field:  "SocialLinkId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeleteProfileSocialLinkRequestMultiError(errors)
	}

	return nil
}

// DeleteProfileSocialLinkRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteProfileSocialLinkRequest.ValidateAll()
// if the designated constraints aren't met.
type DeleteProfileSocialLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteProfileSocialLinkRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteProfileSocialLinkRequestMultiError) AllErrors() []error { return m }

// DeleteProfileSocialLinkRequestValidationError is the validation error
// returned by DeleteProfileSocialLinkRequest.Validate if the designated
// constraints aren't met.
type DeleteProfileSocialLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteProfileSocialLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteProfileSocialLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteProfileSocialLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteProfileSocialLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteProfileSocialLinkRequestValidationError) ErrorName() string {
	return "DeleteProfileSocialLinkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteProfileSocialLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteProfileSocialLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteProfileSocialLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteProfileSocialLinkRequestValidationError{}

// Validate checks the field values on FollowUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *FollowUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FollowUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FollowUserRequestMultiError, or nil if none found.
func (m *FollowUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FollowUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetFolloweeId() == nil {
		err := FollowUserRequestValidationError{
			field:  "FolloweeId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetFolloweeId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FollowUserRequestValidationError{
					field:  "FolloweeId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FollowUserRequestValidationError{
					field:  "FolloweeId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFolloweeId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FollowUserRequestValidationError{
				field:  "FolloweeId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FollowUserRequestMultiError(errors)
	}

	return nil
}

// FollowUserRequestMultiError is an error wrapping multiple validation errors
// returned by FollowUserRequest.ValidateAll() if the designated constraints
// aren't met.
type FollowUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FollowUserRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FollowUserRequestMultiError) AllErrors() []error { return m }

// FollowUserRequestValidationError is the validation error returned by
// FollowUserRequest.Validate if the designated constraints aren't met.
type FollowUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FollowUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FollowUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FollowUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FollowUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FollowUserRequestValidationError) ErrorName() string {
	return "FollowUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FollowUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFollowUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FollowUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FollowUserRequestValidationError{}

// Validate checks the field values on UnfollowUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UnfollowUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnfollowUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UnfollowUserRequestMultiError, or nil if none found.
func (m *UnfollowUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UnfollowUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetFolloweeId() == nil {
		err := UnfollowUserRequestValidationError{
			field:  "FolloweeId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetFolloweeId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UnfollowUserRequestValidationError{
					field:  "FolloweeId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UnfollowUserRequestValidationError{
					field:  "FolloweeId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFolloweeId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UnfollowUserRequestValidationError{
				field:  "FolloweeId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UnfollowUserRequestMultiError(errors)
	}

	return nil
}

// UnfollowUserRequestMultiError is an error wrapping multiple validation
// errors returned by UnfollowUserRequest.ValidateAll() if the designated
// constraints aren't met.
type UnfollowUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnfollowUserRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnfollowUserRequestMultiError) AllErrors() []error { return m }

// UnfollowUserRequestValidationError is the validation error returned by
// UnfollowUserRequest.Validate if the designated constraints aren't met.
type UnfollowUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnfollowUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnfollowUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnfollowUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnfollowUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnfollowUserRequestValidationError) ErrorName() string {
	return "UnfollowUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UnfollowUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnfollowUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnfollowUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnfollowUserRequestValidationError{}

// Validate checks the field values on ListFollowersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListFollowersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListFollowersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListFollowersRequestMultiError, or nil if none found.
func (m *ListFollowersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListFollowersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() == nil {
		err := ListFollowersRequestValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListFollowersRequestValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListFollowersRequestValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListFollowersRequestValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if val := m.GetLimit(); val < 1 || val > 100 {
		err := ListFollowersRequestValidationError{
			field:  "Limit",
			reason: "value must be inside range [1, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListFollowersRequestMultiError(errors)
	}

	return nil
}

// ListFollowersRequestMultiError is an error wrapping multiple validation
// errors returned by ListFollowersRequest.ValidateAll() if the designated
// constraints aren't met.
type ListFollowersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListFollowersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListFollowersRequestMultiError) AllErrors() []error { return m }

// ListFollowersRequestValidationError is the validation error returned by
// ListFollowersRequest.Validate if the designated constraints aren't met.
type ListFollowersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFollowersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFollowersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFollowersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFollowersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFollowersRequestValidationError) ErrorName() string {
	return "ListFollowersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListFollowersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFollowersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFollowersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFollowersRequestValidationError{}

// Validate checks the field values on ListFollowingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListFollowingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListFollowingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListFollowingRequestMultiError, or nil if none found.
func (m *ListFollowingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListFollowingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() == nil {
		err := ListFollowingRequestValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListFollowingRequestValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListFollowingRequestValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListFollowingRequestValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if val := m.GetLimit(); val < 1 || val > 100 {
		err := ListFollowingRequestValidationError{
			field:  "Limit",
			reason: "value must be inside range [1, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListFollowingRequestMultiError(errors)
	}

	return nil
}

// ListFollowingRequestMultiError is an error wrapping multiple validation
// errors returned by ListFollowingRequest.ValidateAll() if the designated
// constraints aren't met.
type ListFollowingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListFollowingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListFollowingRequestMultiError) AllErrors() []error { return m }

// ListFollowingRequestValidationError is the validation error returned by
// ListFollowingRequest.Validate if the designated constraints aren't met.
type ListFollowingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFollowingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFollowingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFollowingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFollowingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFollowingRequestValidationError) ErrorName() string {
	return "ListFollowingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListFollowingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFollowingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFollowingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFollowingRequestValidationError{}

// Validate checks the field values on ListProfilePreviewsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListProfilePreviewsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProfilePreviewsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListProfilePreviewsResponseMultiError, or nil if none found.
func (m *ListProfilePreviewsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProfilePreviewsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProfiles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListProfilePreviewsResponseValidationError{
						field:  fmt.Sprintf("Profiles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListProfilePreviewsResponseValidationError{
						field:  fmt.Sprintf("Profiles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListProfilePreviewsResponseValidationError{
					field:  fmt.Sprintf("Profiles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListProfilePreviewsResponseMultiError(errors)
	}

	return nil
}

// ListProfilePreviewsResponseMultiError is an error wrapping multiple
// validation errors returned by ListProfilePreviewsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListProfilePreviewsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProfilePreviewsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProfilePreviewsResponseMultiError) AllErrors() []error { return m }

// ListProfilePreviewsResponseValidationError is the validation error returned
// by ListProfilePreviewsResponse.Validate if the designated constraints
// aren't met.
type ListProfilePreviewsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProfilePreviewsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProfilePreviewsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProfilePreviewsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProfilePreviewsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProfilePreviewsResponseValidationError) ErrorName() string {
	return "ListProfilePreviewsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListProfilePreviewsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProfilePreviewsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProfilePreviewsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProfilePreviewsResponseValidationError{}

// Validate checks the field values on ListAvailableTitlesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAvailableTitlesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAvailableTitlesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAvailableTitlesResponseMultiError, or nil if none found.
func (m *ListAvailableTitlesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAvailableTitlesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTitles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAvailableTitlesResponseValidationError{
						field:  fmt.Sprintf("Titles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAvailableTitlesResponseValidationError{
						field:  fmt.Sprintf("Titles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAvailableTitlesResponseValidationError{
					field:  fmt.Sprintf("Titles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListAvailableTitlesResponseMultiError(errors)
	}

	return nil
}

// ListAvailableTitlesResponseMultiError is an error wrapping multiple
// validation errors returned by ListAvailableTitlesResponse.ValidateAll() if
// the designated constraints aren't met.
type ListAvailableTitlesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAvailableTitlesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAvailableTitlesResponseMultiError) AllErrors() []error { return m }

// ListAvailableTitlesResponseValidationError is the validation error returned
// by ListAvailableTitlesResponse.Validate if the designated constraints
// aren't met.
type ListAvailableTitlesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAvailableTitlesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAvailableTitlesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAvailableTitlesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAvailableTitlesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAvailableTitlesResponseValidationError) ErrorName() string {
	return "ListAvailableTitlesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListAvailableTitlesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAvailableTitlesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAvailableTitlesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAvailableTitlesResponseValidationError{}

// Validate checks the field values on SetProfileTitleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetProfileTitleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetProfileTitleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetProfileTitleRequestMultiError, or nil if none found.
func (m *SetProfileTitleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetProfileTitleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetTitleCode()); l < 1 || l > 64 {
		err := SetProfileTitleRequestValidationError{
			field:  "TitleCode",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SetProfileTitleRequestMultiError(errors)
	}

	return nil
}

// SetProfileTitleRequestMultiError is an error wrapping multiple validation
// errors returned by SetProfileTitleRequest.ValidateAll() if the designated
// constraints aren't met.
type SetProfileTitleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetProfileTitleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetProfileTitleRequestMultiError) AllErrors() []error { return m }

// SetProfileTitleRequestValidationError is the validation error returned by
// SetProfileTitleRequest.Validate if the designated constraints aren't met.
type SetProfileTitleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetProfileTitleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetProfileTitleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetProfileTitleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetProfileTitleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetProfileTitleRequestValidationError) ErrorName() string {
	return "SetProfileTitleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetProfileTitleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetProfileTitleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetProfileTitleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetProfileTitleRequestValidationError{}
