// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: profile/v1/profile.proto

package profilev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileService_GetMyProfile_FullMethodName            = "/forklore.profile.v1.ProfileService/GetMyProfile"
	ProfileService_GetProfileByUserId_FullMethodName      = "/forklore.profile.v1.ProfileService/GetProfileByUserId"
	ProfileService_GetProfileByUsername_FullMethodName    = "/forklore.profile.v1.ProfileService/GetProfileByUsername"
	ProfileService_UpdateProfile_FullMethodName           = "/forklore.profile.v1.ProfileService/UpdateProfile"
	ProfileService_UpdateProfileReadme_FullMethodName     = "/forklore.profile.v1.ProfileService/UpdateProfileReadme"
	ProfileService_ListProfileSocialLinks_FullMethodName  = "/forklore.profile.v1.ProfileService/ListProfileSocialLinks"
	ProfileService_UpsertProfileSocialLink_FullMethodName = "/forklore.profile.v1.ProfileService/UpsertProfileSocialLink"
	ProfileService_DeleteProfileSocialLink_FullMethodName = "/forklore.profile.v1.ProfileService/DeleteProfileSocialLink"
	ProfileService_FollowUser_FullMethodName              = "/forklore.profile.v1.ProfileService/FollowUser"
	ProfileService_UnfollowUser_FullMethodName            = "/forklore.profile.v1.ProfileService/UnfollowUser"
	ProfileService_ListFollowers_FullMethodName           = "/forklore.profile.v1.ProfileService/ListFollowers"
	ProfileService_ListFollowing_FullMethodName           = "/forklore.profile.v1.ProfileService/ListFollowing"
	ProfileService_ListAvailableTitles_FullMethodName     = "/forklore.profile.v1.ProfileService/ListAvailableTitles"
	ProfileService_SetProfileTitle_FullMethodName         = "/forklore.profile.v1.ProfileService/SetProfileTitle"
)

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileServiceClient interface {
	GetMyProfile(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetProfileResponse, error)
	GetProfileByUserId(ctx context.Context, in *GetProfileByUserIdRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	GetProfileByUsername(ctx context.Context, in *GetProfileByUsernameRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	UpdateProfileReadme(ctx context.Context, in *UpdateProfileReadmeRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	ListProfileSocialLinks(ctx context.Context, in *ListProfileSocialLinksRequest, opts ...grpc.CallOption) (*ListProfileSocialLinksResponse, error)
	UpsertProfileSocialLink(ctx context.Context, in *UpsertProfileSocialLinkRequest, opts ...grpc.CallOption) (*UpsertProfileSocialLinkResponse, error)
	DeleteProfileSocialLink(ctx context.Context, in *DeleteProfileSocialLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListFollowers(ctx context.Context, in *ListFollowersRequest, opts ...grpc.CallOption) (*ListProfilePreviewsResponse, error)
	ListFollowing(ctx context.Context, in *ListFollowingRequest, opts ...grpc.CallOption) (*ListProfilePreviewsResponse, error)
	ListAvailableTitles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAvailableTitlesResponse, error)
	SetProfileTitle(ctx context.Context, in *SetProfileTitleRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) GetMyProfile(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetMyProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetProfileByUserId(ctx context.Context, in *GetProfileByUserIdRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetProfileByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetProfileByUsername(ctx context.Context, in *GetProfileByUsernameRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetProfileByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateProfileReadme(ctx context.Context, in *UpdateProfileReadmeRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_UpdateProfileReadme_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListProfileSocialLinks(ctx context.Context, in *ListProfileSocialLinksRequest, opts ...grpc.CallOption) (*ListProfileSocialLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfileSocialLinksResponse)
	err := c.cc.Invoke(ctx, ProfileService_ListProfileSocialLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpsertProfileSocialLink(ctx context.Context, in *UpsertProfileSocialLinkRequest, opts ...grpc.CallOption) (*UpsertProfileSocialLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertProfileSocialLinkResponse)
	err := c.cc.Invoke(ctx, ProfileService_UpsertProfileSocialLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) DeleteProfileSocialLink(ctx context.Context, in *DeleteProfileSocialLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProfileService_DeleteProfileSocialLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProfileService_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProfileService_UnfollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListFollowers(ctx context.Context, in *ListFollowersRequest, opts ...grpc.CallOption) (*ListProfilePreviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilePreviewsResponse)
	err := c.cc.Invoke(ctx, ProfileService_ListFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListFollowing(ctx context.Context, in *ListFollowingRequest, opts ...grpc.CallOption) (*ListProfilePreviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilePreviewsResponse)
	err := c.cc.Invoke(ctx, ProfileService_ListFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListAvailableTitles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAvailableTitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailableTitlesResponse)
	err := c.cc.Invoke(ctx, ProfileService_ListAvailableTitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) SetProfileTitle(ctx context.Context, in *SetProfileTitleRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_SetProfileTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
// All implementations must embed UnimplementedProfileServiceServer
// for forward compatibility.
type ProfileServiceServer interface {
	GetMyProfile(context.Context, *emptypb.Empty) (*GetProfileResponse, error)
	GetProfileByUserId(context.Context, *GetProfileByUserIdRequest) (*GetProfileResponse, error)
	GetProfileByUsername(context.Context, *GetProfileByUsernameRequest) (*GetProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	UpdateProfileReadme(context.Context, *UpdateProfileReadmeRequest) (*UpdateProfileResponse, error)
	ListProfileSocialLinks(context.Context, *ListProfileSocialLinksRequest) (*ListProfileSocialLinksResponse, error)
	UpsertProfileSocialLink(context.Context, *UpsertProfileSocialLinkRequest) (*UpsertProfileSocialLinkResponse, error)
	DeleteProfileSocialLink(context.Context, *DeleteProfileSocialLinkRequest) (*emptypb.Empty, error)
	FollowUser(context.Context, *FollowUserRequest) (*emptypb.Empty, error)
	UnfollowUser(context.Context, *UnfollowUserRequest) (*emptypb.Empty, error)
	ListFollowers(context.Context, *ListFollowersRequest) (*ListProfilePreviewsResponse, error)
	ListFollowing(context.Context, *ListFollowingRequest) (*ListProfilePreviewsResponse, error)
	ListAvailableTitles(context.Context, *emptypb.Empty) (*ListAvailableTitlesResponse, error)
	SetProfileTitle(context.Context, *SetProfileTitleRequest) (*UpdateProfileResponse, error)
	mustEmbedUnimplementedProfileServiceServer()
}

// UnimplementedProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileServiceServer struct{}

func (UnimplementedProfileServiceServer) GetMyProfile(context.Context, *emptypb.Empty) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyProfile not implemented")
}
func (UnimplementedProfileServiceServer) GetProfileByUserId(context.Context, *GetProfileByUserIdRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileByUserId not implemented")
}
func (UnimplementedProfileServiceServer) GetProfileByUsername(context.Context, *GetProfileByUsernameRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileByUsername not implemented")
}
func (UnimplementedProfileServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedProfileServiceServer) UpdateProfileReadme(context.Context, *UpdateProfileReadmeRequest) (*UpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfileReadme not implemented")
}
func (UnimplementedProfileServiceServer) ListProfileSocialLinks(context.Context, *ListProfileSocialLinksRequest) (*ListProfileSocialLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfileSocialLinks not implemented")
}
func (UnimplementedProfileServiceServer) UpsertProfileSocialLink(context.Context, *UpsertProfileSocialLinkRequest) (*UpsertProfileSocialLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertProfileSocialLink not implemented")
}
func (UnimplementedProfileServiceServer) DeleteProfileSocialLink(context.Context, *DeleteProfileSocialLinkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfileSocialLink not implemented")
}
func (UnimplementedProfileServiceServer) FollowUser(context.Context, *FollowUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedProfileServiceServer) UnfollowUser(context.Context, *UnfollowUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfollowUser not implemented")
}
func (UnimplementedProfileServiceServer) ListFollowers(context.Context, *ListFollowersRequest) (*ListProfilePreviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFollowers not implemented")
}
func (UnimplementedProfileServiceServer) ListFollowing(context.Context, *ListFollowingRequest) (*ListProfilePreviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFollowing not implemented")
}
func (UnimplementedProfileServiceServer) ListAvailableTitles(context.Context, *emptypb.Empty) (*ListAvailableTitlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableTitles not implemented")
}
func (UnimplementedProfileServiceServer) SetProfileTitle(context.Context, *SetProfileTitleRequest) (*UpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProfileTitle not implemented")
}
func (UnimplementedProfileServiceServer) mustEmbedUnimplementedProfileServiceServer() {}
func (UnimplementedProfileServiceServer) testEmbeddedByValue()                        {}

// UnsafeProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServiceServer will
// result in compilation errors.
type UnsafeProfileServiceServer interface {
	mustEmbedUnimplementedProfileServiceServer()
}

func RegisterProfileServiceServer(s grpc.ServiceRegistrar, srv ProfileServiceServer) {
	// If the following call pancis, it indicates UnimplementedProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileService_ServiceDesc, srv)
}

func _ProfileService_GetMyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetMyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetMyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetMyProfile(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetProfileByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetProfileByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetProfileByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetProfileByUserId(ctx, req.(*GetProfileByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetProfileByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetProfileByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetProfileByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetProfileByUsername(ctx, req.(*GetProfileByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateProfileReadme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileReadmeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateProfileReadme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpdateProfileReadme_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateProfileReadme(ctx, req.(*UpdateProfileReadmeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListProfileSocialLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfileSocialLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListProfileSocialLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_ListProfileSocialLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListProfileSocialLinks(ctx, req.(*ListProfileSocialLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpsertProfileSocialLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProfileSocialLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpsertProfileSocialLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpsertProfileSocialLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpsertProfileSocialLink(ctx, req.(*UpsertProfileSocialLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_DeleteProfileSocialLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileSocialLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).DeleteProfileSocialLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_DeleteProfileSocialLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).DeleteProfileSocialLink(ctx, req.(*DeleteProfileSocialLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UnfollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UnfollowUser(ctx, req.(*UnfollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_ListFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListFollowers(ctx, req.(*ListFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_ListFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListFollowing(ctx, req.(*ListFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListAvailableTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListAvailableTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_ListAvailableTitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListAvailableTitles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_SetProfileTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProfileTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).SetProfileTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_SetProfileTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).SetProfileTitle(ctx, req.(*SetProfileTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileService_ServiceDesc is the grpc.ServiceDesc for ProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forklore.profile.v1.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyProfile",
			Handler:    _ProfileService_GetMyProfile_Handler,
		},
		{
			MethodName: "GetProfileByUserId",
			Handler:    _ProfileService_GetProfileByUserId_Handler,
		},
		{
			MethodName: "GetProfileByUsername",
			Handler:    _ProfileService_GetProfileByUsername_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _ProfileService_UpdateProfile_Handler,
		},
		{
			MethodName: "UpdateProfileReadme",
			Handler:    _ProfileService_UpdateProfileReadme_Handler,
		},
		{
			MethodName: "ListProfileSocialLinks",
			Handler:    _ProfileService_ListProfileSocialLinks_Handler,
		},
		{
			MethodName: "UpsertProfileSocialLink",
			Handler:    _ProfileService_UpsertProfileSocialLink_Handler,
		},
		{
			MethodName: "DeleteProfileSocialLink",
			Handler:    _ProfileService_DeleteProfileSocialLink_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _ProfileService_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _ProfileService_UnfollowUser_Handler,
		},
		{
			MethodName: "ListFollowers",
			Handler:    _ProfileService_ListFollowers_Handler,
		},
		{
			MethodName: "ListFollowing",
			Handler:    _ProfileService_ListFollowing_Handler,
		},
		{
			MethodName: "ListAvailableTitles",
			Handler:    _ProfileService_ListAvailableTitles_Handler,
		},
		{
			MethodName: "SetProfileTitle",
			Handler:    _ProfileService_SetProfileTitle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile/v1/profile.proto",
}
