// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: search/events/v1/searchevents.proto

package searcheventsv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	commonv1 "github.com/Anabol1ks/Forklore/pkg/pb/common/v1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = commonv1.SearchEventType(0)
)

// Validate checks the field values on SearchEventEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchEventEnvelope) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchEventEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchEventEnvelopeMultiError, or nil if none found.
func (m *SearchEventEnvelope) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchEventEnvelope) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetEventId()); l < 1 || l > 128 {
		err := SearchEventEnvelopeValidationError{
			field:  "EventId",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for EventType

	if m.GetOccurredAt() == nil {
		err := SearchEventEnvelopeValidationError{
			field:  "OccurredAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	switch v := m.Payload.(type) {
	case *SearchEventEnvelope_RepositoryUpserted:
		if v == nil {
			err := SearchEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRepositoryUpserted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "RepositoryUpserted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "RepositoryUpserted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRepositoryUpserted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchEventEnvelopeValidationError{
					field:  "RepositoryUpserted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *SearchEventEnvelope_RepositoryDeleted:
		if v == nil {
			err := SearchEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRepositoryDeleted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "RepositoryDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "RepositoryDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRepositoryDeleted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchEventEnvelopeValidationError{
					field:  "RepositoryDeleted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *SearchEventEnvelope_DocumentUpserted:
		if v == nil {
			err := SearchEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetDocumentUpserted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "DocumentUpserted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "DocumentUpserted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDocumentUpserted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchEventEnvelopeValidationError{
					field:  "DocumentUpserted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *SearchEventEnvelope_DocumentDeleted:
		if v == nil {
			err := SearchEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetDocumentDeleted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "DocumentDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "DocumentDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDocumentDeleted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchEventEnvelopeValidationError{
					field:  "DocumentDeleted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *SearchEventEnvelope_FileUpserted:
		if v == nil {
			err := SearchEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFileUpserted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "FileUpserted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "FileUpserted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFileUpserted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchEventEnvelopeValidationError{
					field:  "FileUpserted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *SearchEventEnvelope_FileDeleted:
		if v == nil {
			err := SearchEventEnvelopeValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFileDeleted()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "FileDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchEventEnvelopeValidationError{
						field:  "FileDeleted",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFileDeleted()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchEventEnvelopeValidationError{
					field:  "FileDeleted",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return SearchEventEnvelopeMultiError(errors)
	}

	return nil
}

// SearchEventEnvelopeMultiError is an error wrapping multiple validation
// errors returned by SearchEventEnvelope.ValidateAll() if the designated
// constraints aren't met.
type SearchEventEnvelopeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchEventEnvelopeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchEventEnvelopeMultiError) AllErrors() []error { return m }

// SearchEventEnvelopeValidationError is the validation error returned by
// SearchEventEnvelope.Validate if the designated constraints aren't met.
type SearchEventEnvelopeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchEventEnvelopeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchEventEnvelopeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchEventEnvelopeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchEventEnvelopeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchEventEnvelopeValidationError) ErrorName() string {
	return "SearchEventEnvelopeValidationError"
}

// Error satisfies the builtin error interface
func (e SearchEventEnvelopeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchEventEnvelope.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchEventEnvelopeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchEventEnvelopeValidationError{}

// Validate checks the field values on RepositoryUpserted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RepositoryUpserted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RepositoryUpserted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RepositoryUpsertedMultiError, or nil if none found.
func (m *RepositoryUpserted) ValidateAll() error {
	return m.validate(true)
}

func (m *RepositoryUpserted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetRepoId() == nil {
		err := RepositoryUpsertedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryUpsertedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryUpsertedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryUpsertedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetOwnerId() == nil {
		err := RepositoryUpsertedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryUpsertedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryUpsertedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryUpsertedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := RepositoryUpsertedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryUpsertedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryUpsertedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryUpsertedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetTitle()); l < 1 || l > 255 {
		err := RepositoryUpsertedValidationError{
			field:  "Title",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) > 4000 {
		err := RepositoryUpsertedValidationError{
			field:  "Description",
			reason: "value length must be at most 4000 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTagName()) > 128 {
		err := RepositoryUpsertedValidationError{
			field:  "TagName",
			reason: "value length must be at most 128 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsPublic

	if m.GetUpdatedAt() == nil {
		err := RepositoryUpsertedValidationError{
			field:  "UpdatedAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RepositoryUpsertedMultiError(errors)
	}

	return nil
}

// RepositoryUpsertedMultiError is an error wrapping multiple validation errors
// returned by RepositoryUpserted.ValidateAll() if the designated constraints
// aren't met.
type RepositoryUpsertedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RepositoryUpsertedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RepositoryUpsertedMultiError) AllErrors() []error { return m }

// RepositoryUpsertedValidationError is the validation error returned by
// RepositoryUpserted.Validate if the designated constraints aren't met.
type RepositoryUpsertedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RepositoryUpsertedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RepositoryUpsertedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RepositoryUpsertedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RepositoryUpsertedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RepositoryUpsertedValidationError) ErrorName() string {
	return "RepositoryUpsertedValidationError"
}

// Error satisfies the builtin error interface
func (e RepositoryUpsertedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRepositoryUpserted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RepositoryUpsertedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RepositoryUpsertedValidationError{}

// Validate checks the field values on RepositoryDeleted with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RepositoryDeleted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RepositoryDeleted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RepositoryDeletedMultiError, or nil if none found.
func (m *RepositoryDeleted) ValidateAll() error {
	return m.validate(true)
}

func (m *RepositoryDeleted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetRepoId() == nil {
		err := RepositoryDeletedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RepositoryDeletedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RepositoryDeletedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RepositoryDeletedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RepositoryDeletedMultiError(errors)
	}

	return nil
}

// RepositoryDeletedMultiError is an error wrapping multiple validation errors
// returned by RepositoryDeleted.ValidateAll() if the designated constraints
// aren't met.
type RepositoryDeletedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RepositoryDeletedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RepositoryDeletedMultiError) AllErrors() []error { return m }

// RepositoryDeletedValidationError is the validation error returned by
// RepositoryDeleted.Validate if the designated constraints aren't met.
type RepositoryDeletedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RepositoryDeletedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RepositoryDeletedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RepositoryDeletedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RepositoryDeletedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RepositoryDeletedValidationError) ErrorName() string {
	return "RepositoryDeletedValidationError"
}

// Error satisfies the builtin error interface
func (e RepositoryDeletedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRepositoryDeleted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RepositoryDeletedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RepositoryDeletedValidationError{}

// Validate checks the field values on DocumentUpserted with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DocumentUpserted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DocumentUpserted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DocumentUpsertedMultiError, or nil if none found.
func (m *DocumentUpserted) ValidateAll() error {
	return m.validate(true)
}

func (m *DocumentUpserted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDocumentId() == nil {
		err := DocumentUpsertedValidationError{
			field:  "DocumentId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetDocumentId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentUpsertedValidationError{
					field:  "DocumentId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentUpsertedValidationError{
					field:  "DocumentId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDocumentId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentUpsertedValidationError{
				field:  "DocumentId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := DocumentUpsertedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentUpsertedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentUpsertedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentUpsertedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetOwnerId() == nil {
		err := DocumentUpsertedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentUpsertedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentUpsertedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentUpsertedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := DocumentUpsertedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentUpsertedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentUpsertedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentUpsertedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetTitle()); l < 1 || l > 255 {
		err := DocumentUpsertedValidationError{
			field:  "Title",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Content

	if utf8.RuneCountInString(m.GetTagName()) > 128 {
		err := DocumentUpsertedValidationError{
			field:  "TagName",
			reason: "value length must be at most 128 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsPublic

	if m.GetUpdatedAt() == nil {
		err := DocumentUpsertedValidationError{
			field:  "UpdatedAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DocumentUpsertedMultiError(errors)
	}

	return nil
}

// DocumentUpsertedMultiError is an error wrapping multiple validation errors
// returned by DocumentUpserted.ValidateAll() if the designated constraints
// aren't met.
type DocumentUpsertedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentUpsertedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentUpsertedMultiError) AllErrors() []error { return m }

// DocumentUpsertedValidationError is the validation error returned by
// DocumentUpserted.Validate if the designated constraints aren't met.
type DocumentUpsertedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentUpsertedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentUpsertedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentUpsertedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentUpsertedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentUpsertedValidationError) ErrorName() string { return "DocumentUpsertedValidationError" }

// Error satisfies the builtin error interface
func (e DocumentUpsertedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocumentUpserted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentUpsertedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentUpsertedValidationError{}

// Validate checks the field values on DocumentDeleted with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DocumentDeleted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DocumentDeleted with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DocumentDeletedMultiError, or nil if none found.
func (m *DocumentDeleted) ValidateAll() error {
	return m.validate(true)
}

func (m *DocumentDeleted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDocumentId() == nil {
		err := DocumentDeletedValidationError{
			field:  "DocumentId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetDocumentId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentDeletedValidationError{
					field:  "DocumentId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentDeletedValidationError{
					field:  "DocumentId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDocumentId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentDeletedValidationError{
				field:  "DocumentId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DocumentDeletedMultiError(errors)
	}

	return nil
}

// DocumentDeletedMultiError is an error wrapping multiple validation errors
// returned by DocumentDeleted.ValidateAll() if the designated constraints
// aren't met.
type DocumentDeletedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentDeletedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentDeletedMultiError) AllErrors() []error { return m }

// DocumentDeletedValidationError is the validation error returned by
// DocumentDeleted.Validate if the designated constraints aren't met.
type DocumentDeletedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentDeletedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentDeletedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentDeletedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentDeletedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentDeletedValidationError) ErrorName() string { return "DocumentDeletedValidationError" }

// Error satisfies the builtin error interface
func (e DocumentDeletedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocumentDeleted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentDeletedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentDeletedValidationError{}

// Validate checks the field values on FileUpserted with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FileUpserted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileUpserted with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FileUpsertedMultiError, or
// nil if none found.
func (m *FileUpserted) ValidateAll() error {
	return m.validate(true)
}

func (m *FileUpserted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetFileId() == nil {
		err := FileUpsertedValidationError{
			field:  "FileId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetFileId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileUpsertedValidationError{
					field:  "FileId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileUpsertedValidationError{
					field:  "FileId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFileId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileUpsertedValidationError{
				field:  "FileId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRepoId() == nil {
		err := FileUpsertedValidationError{
			field:  "RepoId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRepoId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileUpsertedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileUpsertedValidationError{
					field:  "RepoId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepoId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileUpsertedValidationError{
				field:  "RepoId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetOwnerId() == nil {
		err := FileUpsertedValidationError{
			field:  "OwnerId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetOwnerId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileUpsertedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileUpsertedValidationError{
					field:  "OwnerId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwnerId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileUpsertedValidationError{
				field:  "OwnerId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTagId() == nil {
		err := FileUpsertedValidationError{
			field:  "TagId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTagId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileUpsertedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileUpsertedValidationError{
					field:  "TagId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTagId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileUpsertedValidationError{
				field:  "TagId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetFileName()); l < 1 || l > 255 {
		err := FileUpsertedValidationError{
			field:  "FileName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetMimeType()) > 255 {
		err := FileUpsertedValidationError{
			field:  "MimeType",
			reason: "value length must be at most 255 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTagName()) > 128 {
		err := FileUpsertedValidationError{
			field:  "TagName",
			reason: "value length must be at most 128 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsPublic

	if m.GetUpdatedAt() == nil {
		err := FileUpsertedValidationError{
			field:  "UpdatedAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FileUpsertedMultiError(errors)
	}

	return nil
}

// FileUpsertedMultiError is an error wrapping multiple validation errors
// returned by FileUpserted.ValidateAll() if the designated constraints aren't met.
type FileUpsertedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileUpsertedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileUpsertedMultiError) AllErrors() []error { return m }

// FileUpsertedValidationError is the validation error returned by
// FileUpserted.Validate if the designated constraints aren't met.
type FileUpsertedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileUpsertedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileUpsertedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileUpsertedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileUpsertedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileUpsertedValidationError) ErrorName() string { return "FileUpsertedValidationError" }

// Error satisfies the builtin error interface
func (e FileUpsertedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileUpserted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileUpsertedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileUpsertedValidationError{}

// Validate checks the field values on FileDeleted with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FileDeleted) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileDeleted with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FileDeletedMultiError, or
// nil if none found.
func (m *FileDeleted) ValidateAll() error {
	return m.validate(true)
}

func (m *FileDeleted) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetFileId() == nil {
		err := FileDeletedValidationError{
			field:  "FileId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetFileId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileDeletedValidationError{
					field:  "FileId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileDeletedValidationError{
					field:  "FileId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFileId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileDeletedValidationError{
				field:  "FileId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FileDeletedMultiError(errors)
	}

	return nil
}

// FileDeletedMultiError is an error wrapping multiple validation errors
// returned by FileDeleted.ValidateAll() if the designated constraints aren't met.
type FileDeletedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileDeletedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileDeletedMultiError) AllErrors() []error { return m }

// FileDeletedValidationError is the validation error returned by
// FileDeleted.Validate if the designated constraints aren't met.
type FileDeletedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileDeletedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileDeletedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileDeletedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileDeletedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileDeletedValidationError) ErrorName() string { return "FileDeletedValidationError" }

// Error satisfies the builtin error interface
func (e FileDeletedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileDeleted.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileDeletedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileDeletedValidationError{}
